// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/akakou/ra_webs/ttp/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/akakou/ra_webs/ttp/ent/ctaudit"
	"github.com/akakou/ra_webs/ttp/ent/service"
	"github.com/akakou/ra_webs/ttp/ent/ta"
	"github.com/akakou/ra_webs/ttp/ent/tacode"
	"github.com/akakou/ra_webs/ttp/ent/taserver"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CTAudit is the client for interacting with the CTAudit builders.
	CTAudit *CTAuditClient
	// Service is the client for interacting with the Service builders.
	Service *ServiceClient
	// TA is the client for interacting with the TA builders.
	TA *TAClient
	// TACode is the client for interacting with the TACode builders.
	TACode *TACodeClient
	// TAServer is the client for interacting with the TAServer builders.
	TAServer *TAServerClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CTAudit = NewCTAuditClient(c.config)
	c.Service = NewServiceClient(c.config)
	c.TA = NewTAClient(c.config)
	c.TACode = NewTACodeClient(c.config)
	c.TAServer = NewTAServerClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		CTAudit:  NewCTAuditClient(cfg),
		Service:  NewServiceClient(cfg),
		TA:       NewTAClient(cfg),
		TACode:   NewTACodeClient(cfg),
		TAServer: NewTAServerClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		CTAudit:  NewCTAuditClient(cfg),
		Service:  NewServiceClient(cfg),
		TA:       NewTAClient(cfg),
		TACode:   NewTACodeClient(cfg),
		TAServer: NewTAServerClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CTAudit.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.CTAudit.Use(hooks...)
	c.Service.Use(hooks...)
	c.TA.Use(hooks...)
	c.TACode.Use(hooks...)
	c.TAServer.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.CTAudit.Intercept(interceptors...)
	c.Service.Intercept(interceptors...)
	c.TA.Intercept(interceptors...)
	c.TACode.Intercept(interceptors...)
	c.TAServer.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CTAuditMutation:
		return c.CTAudit.mutate(ctx, m)
	case *ServiceMutation:
		return c.Service.mutate(ctx, m)
	case *TAMutation:
		return c.TA.mutate(ctx, m)
	case *TACodeMutation:
		return c.TACode.mutate(ctx, m)
	case *TAServerMutation:
		return c.TAServer.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CTAuditClient is a client for the CTAudit schema.
type CTAuditClient struct {
	config
}

// NewCTAuditClient returns a client for the CTAudit from the given config.
func NewCTAuditClient(c config) *CTAuditClient {
	return &CTAuditClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ctaudit.Hooks(f(g(h())))`.
func (c *CTAuditClient) Use(hooks ...Hook) {
	c.hooks.CTAudit = append(c.hooks.CTAudit, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ctaudit.Intercept(f(g(h())))`.
func (c *CTAuditClient) Intercept(interceptors ...Interceptor) {
	c.inters.CTAudit = append(c.inters.CTAudit, interceptors...)
}

// Create returns a builder for creating a CTAudit entity.
func (c *CTAuditClient) Create() *CTAuditCreate {
	mutation := newCTAuditMutation(c.config, OpCreate)
	return &CTAuditCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CTAudit entities.
func (c *CTAuditClient) CreateBulk(builders ...*CTAuditCreate) *CTAuditCreateBulk {
	return &CTAuditCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CTAuditClient) MapCreateBulk(slice any, setFunc func(*CTAuditCreate, int)) *CTAuditCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CTAuditCreateBulk{err: fmt.Errorf("calling to CTAuditClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CTAuditCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CTAuditCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CTAudit.
func (c *CTAuditClient) Update() *CTAuditUpdate {
	mutation := newCTAuditMutation(c.config, OpUpdate)
	return &CTAuditUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CTAuditClient) UpdateOne(ca *CTAudit) *CTAuditUpdateOne {
	mutation := newCTAuditMutation(c.config, OpUpdateOne, withCTAudit(ca))
	return &CTAuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CTAuditClient) UpdateOneID(id int) *CTAuditUpdateOne {
	mutation := newCTAuditMutation(c.config, OpUpdateOne, withCTAuditID(id))
	return &CTAuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CTAudit.
func (c *CTAuditClient) Delete() *CTAuditDelete {
	mutation := newCTAuditMutation(c.config, OpDelete)
	return &CTAuditDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CTAuditClient) DeleteOne(ca *CTAudit) *CTAuditDeleteOne {
	return c.DeleteOneID(ca.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CTAuditClient) DeleteOneID(id int) *CTAuditDeleteOne {
	builder := c.Delete().Where(ctaudit.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CTAuditDeleteOne{builder}
}

// Query returns a query builder for CTAudit.
func (c *CTAuditClient) Query() *CTAuditQuery {
	return &CTAuditQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCTAudit},
		inters: c.Interceptors(),
	}
}

// Get returns a CTAudit entity by its id.
func (c *CTAuditClient) Get(ctx context.Context, id int) (*CTAudit, error) {
	return c.Query().Where(ctaudit.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CTAuditClient) GetX(ctx context.Context, id int) *CTAudit {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTa queries the ta edge of a CTAudit.
func (c *CTAuditClient) QueryTa(ca *CTAudit) *TAQuery {
	query := (&TAClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ca.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ctaudit.Table, ctaudit.FieldID, id),
			sqlgraph.To(ta.Table, ta.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ctaudit.TaTable, ctaudit.TaColumn),
		)
		fromV = sqlgraph.Neighbors(ca.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CTAuditClient) Hooks() []Hook {
	return c.hooks.CTAudit
}

// Interceptors returns the client interceptors.
func (c *CTAuditClient) Interceptors() []Interceptor {
	return c.inters.CTAudit
}

func (c *CTAuditClient) mutate(ctx context.Context, m *CTAuditMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CTAuditCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CTAuditUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CTAuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CTAuditDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CTAudit mutation op: %q", m.Op())
	}
}

// ServiceClient is a client for the Service schema.
type ServiceClient struct {
	config
}

// NewServiceClient returns a client for the Service from the given config.
func NewServiceClient(c config) *ServiceClient {
	return &ServiceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `service.Hooks(f(g(h())))`.
func (c *ServiceClient) Use(hooks ...Hook) {
	c.hooks.Service = append(c.hooks.Service, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `service.Intercept(f(g(h())))`.
func (c *ServiceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Service = append(c.inters.Service, interceptors...)
}

// Create returns a builder for creating a Service entity.
func (c *ServiceClient) Create() *ServiceCreate {
	mutation := newServiceMutation(c.config, OpCreate)
	return &ServiceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Service entities.
func (c *ServiceClient) CreateBulk(builders ...*ServiceCreate) *ServiceCreateBulk {
	return &ServiceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ServiceClient) MapCreateBulk(slice any, setFunc func(*ServiceCreate, int)) *ServiceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ServiceCreateBulk{err: fmt.Errorf("calling to ServiceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ServiceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ServiceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Service.
func (c *ServiceClient) Update() *ServiceUpdate {
	mutation := newServiceMutation(c.config, OpUpdate)
	return &ServiceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ServiceClient) UpdateOne(s *Service) *ServiceUpdateOne {
	mutation := newServiceMutation(c.config, OpUpdateOne, withService(s))
	return &ServiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ServiceClient) UpdateOneID(id int) *ServiceUpdateOne {
	mutation := newServiceMutation(c.config, OpUpdateOne, withServiceID(id))
	return &ServiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Service.
func (c *ServiceClient) Delete() *ServiceDelete {
	mutation := newServiceMutation(c.config, OpDelete)
	return &ServiceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ServiceClient) DeleteOne(s *Service) *ServiceDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ServiceClient) DeleteOneID(id int) *ServiceDeleteOne {
	builder := c.Delete().Where(service.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ServiceDeleteOne{builder}
}

// Query returns a query builder for Service.
func (c *ServiceClient) Query() *ServiceQuery {
	return &ServiceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeService},
		inters: c.Interceptors(),
	}
}

// Get returns a Service entity by its id.
func (c *ServiceClient) Get(ctx context.Context, id int) (*Service, error) {
	return c.Query().Where(service.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ServiceClient) GetX(ctx context.Context, id int) *Service {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTaserver queries the taserver edge of a Service.
func (c *ServiceClient) QueryTaserver(s *Service) *TAServerQuery {
	query := (&TAServerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(service.Table, service.FieldID, id),
			sqlgraph.To(taserver.Table, taserver.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, service.TaserverTable, service.TaserverColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTacode queries the tacode edge of a Service.
func (c *ServiceClient) QueryTacode(s *Service) *TACodeQuery {
	query := (&TACodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(service.Table, service.FieldID, id),
			sqlgraph.To(tacode.Table, tacode.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, service.TacodeTable, service.TacodeColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ServiceClient) Hooks() []Hook {
	return c.hooks.Service
}

// Interceptors returns the client interceptors.
func (c *ServiceClient) Interceptors() []Interceptor {
	return c.inters.Service
}

func (c *ServiceClient) mutate(ctx context.Context, m *ServiceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ServiceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ServiceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ServiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ServiceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Service mutation op: %q", m.Op())
	}
}

// TAClient is a client for the TA schema.
type TAClient struct {
	config
}

// NewTAClient returns a client for the TA from the given config.
func NewTAClient(c config) *TAClient {
	return &TAClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ta.Hooks(f(g(h())))`.
func (c *TAClient) Use(hooks ...Hook) {
	c.hooks.TA = append(c.hooks.TA, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ta.Intercept(f(g(h())))`.
func (c *TAClient) Intercept(interceptors ...Interceptor) {
	c.inters.TA = append(c.inters.TA, interceptors...)
}

// Create returns a builder for creating a TA entity.
func (c *TAClient) Create() *TACreate {
	mutation := newTAMutation(c.config, OpCreate)
	return &TACreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TA entities.
func (c *TAClient) CreateBulk(builders ...*TACreate) *TACreateBulk {
	return &TACreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TAClient) MapCreateBulk(slice any, setFunc func(*TACreate, int)) *TACreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TACreateBulk{err: fmt.Errorf("calling to TAClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TACreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TACreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TA.
func (c *TAClient) Update() *TAUpdate {
	mutation := newTAMutation(c.config, OpUpdate)
	return &TAUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TAClient) UpdateOne(t *TA) *TAUpdateOne {
	mutation := newTAMutation(c.config, OpUpdateOne, withTA(t))
	return &TAUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TAClient) UpdateOneID(id int) *TAUpdateOne {
	mutation := newTAMutation(c.config, OpUpdateOne, withTAID(id))
	return &TAUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TA.
func (c *TAClient) Delete() *TADelete {
	mutation := newTAMutation(c.config, OpDelete)
	return &TADelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TAClient) DeleteOne(t *TA) *TADeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TAClient) DeleteOneID(id int) *TADeleteOne {
	builder := c.Delete().Where(ta.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TADeleteOne{builder}
}

// Query returns a query builder for TA.
func (c *TAClient) Query() *TAQuery {
	return &TAQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTA},
		inters: c.Interceptors(),
	}
}

// Get returns a TA entity by its id.
func (c *TAClient) Get(ctx context.Context, id int) (*TA, error) {
	return c.Query().Where(ta.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TAClient) GetX(ctx context.Context, id int) *TA {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCode queries the code edge of a TA.
func (c *TAClient) QueryCode(t *TA) *TACodeQuery {
	query := (&TACodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ta.Table, ta.FieldID, id),
			sqlgraph.To(tacode.Table, tacode.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ta.CodeTable, ta.CodeColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryServer queries the server edge of a TA.
func (c *TAClient) QueryServer(t *TA) *TAServerQuery {
	query := (&TAServerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ta.Table, ta.FieldID, id),
			sqlgraph.To(taserver.Table, taserver.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ta.ServerTable, ta.ServerColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCtAudit queries the ct_audit edge of a TA.
func (c *TAClient) QueryCtAudit(t *TA) *CTAuditQuery {
	query := (&CTAuditClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ta.Table, ta.FieldID, id),
			sqlgraph.To(ctaudit.Table, ctaudit.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ta.CtAuditTable, ta.CtAuditColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TAClient) Hooks() []Hook {
	return c.hooks.TA
}

// Interceptors returns the client interceptors.
func (c *TAClient) Interceptors() []Interceptor {
	return c.inters.TA
}

func (c *TAClient) mutate(ctx context.Context, m *TAMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TACreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TAUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TAUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TADelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TA mutation op: %q", m.Op())
	}
}

// TACodeClient is a client for the TACode schema.
type TACodeClient struct {
	config
}

// NewTACodeClient returns a client for the TACode from the given config.
func NewTACodeClient(c config) *TACodeClient {
	return &TACodeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tacode.Hooks(f(g(h())))`.
func (c *TACodeClient) Use(hooks ...Hook) {
	c.hooks.TACode = append(c.hooks.TACode, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tacode.Intercept(f(g(h())))`.
func (c *TACodeClient) Intercept(interceptors ...Interceptor) {
	c.inters.TACode = append(c.inters.TACode, interceptors...)
}

// Create returns a builder for creating a TACode entity.
func (c *TACodeClient) Create() *TACodeCreate {
	mutation := newTACodeMutation(c.config, OpCreate)
	return &TACodeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TACode entities.
func (c *TACodeClient) CreateBulk(builders ...*TACodeCreate) *TACodeCreateBulk {
	return &TACodeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TACodeClient) MapCreateBulk(slice any, setFunc func(*TACodeCreate, int)) *TACodeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TACodeCreateBulk{err: fmt.Errorf("calling to TACodeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TACodeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TACodeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TACode.
func (c *TACodeClient) Update() *TACodeUpdate {
	mutation := newTACodeMutation(c.config, OpUpdate)
	return &TACodeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TACodeClient) UpdateOne(tc *TACode) *TACodeUpdateOne {
	mutation := newTACodeMutation(c.config, OpUpdateOne, withTACode(tc))
	return &TACodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TACodeClient) UpdateOneID(id int) *TACodeUpdateOne {
	mutation := newTACodeMutation(c.config, OpUpdateOne, withTACodeID(id))
	return &TACodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TACode.
func (c *TACodeClient) Delete() *TACodeDelete {
	mutation := newTACodeMutation(c.config, OpDelete)
	return &TACodeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TACodeClient) DeleteOne(tc *TACode) *TACodeDeleteOne {
	return c.DeleteOneID(tc.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TACodeClient) DeleteOneID(id int) *TACodeDeleteOne {
	builder := c.Delete().Where(tacode.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TACodeDeleteOne{builder}
}

// Query returns a query builder for TACode.
func (c *TACodeClient) Query() *TACodeQuery {
	return &TACodeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTACode},
		inters: c.Interceptors(),
	}
}

// Get returns a TACode entity by its id.
func (c *TACodeClient) Get(ctx context.Context, id int) (*TACode, error) {
	return c.Query().Where(tacode.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TACodeClient) GetX(ctx context.Context, id int) *TACode {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTa queries the ta edge of a TACode.
func (c *TACodeClient) QueryTa(tc *TACode) *TAQuery {
	query := (&TAClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := tc.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tacode.Table, tacode.FieldID, id),
			sqlgraph.To(ta.Table, ta.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, tacode.TaTable, tacode.TaColumn),
		)
		fromV = sqlgraph.Neighbors(tc.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryService queries the service edge of a TACode.
func (c *TACodeClient) QueryService(tc *TACode) *ServiceQuery {
	query := (&ServiceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := tc.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tacode.Table, tacode.FieldID, id),
			sqlgraph.To(service.Table, service.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, tacode.ServiceTable, tacode.ServiceColumn),
		)
		fromV = sqlgraph.Neighbors(tc.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TACodeClient) Hooks() []Hook {
	return c.hooks.TACode
}

// Interceptors returns the client interceptors.
func (c *TACodeClient) Interceptors() []Interceptor {
	return c.inters.TACode
}

func (c *TACodeClient) mutate(ctx context.Context, m *TACodeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TACodeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TACodeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TACodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TACodeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TACode mutation op: %q", m.Op())
	}
}

// TAServerClient is a client for the TAServer schema.
type TAServerClient struct {
	config
}

// NewTAServerClient returns a client for the TAServer from the given config.
func NewTAServerClient(c config) *TAServerClient {
	return &TAServerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `taserver.Hooks(f(g(h())))`.
func (c *TAServerClient) Use(hooks ...Hook) {
	c.hooks.TAServer = append(c.hooks.TAServer, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `taserver.Intercept(f(g(h())))`.
func (c *TAServerClient) Intercept(interceptors ...Interceptor) {
	c.inters.TAServer = append(c.inters.TAServer, interceptors...)
}

// Create returns a builder for creating a TAServer entity.
func (c *TAServerClient) Create() *TAServerCreate {
	mutation := newTAServerMutation(c.config, OpCreate)
	return &TAServerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TAServer entities.
func (c *TAServerClient) CreateBulk(builders ...*TAServerCreate) *TAServerCreateBulk {
	return &TAServerCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TAServerClient) MapCreateBulk(slice any, setFunc func(*TAServerCreate, int)) *TAServerCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TAServerCreateBulk{err: fmt.Errorf("calling to TAServerClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TAServerCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TAServerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TAServer.
func (c *TAServerClient) Update() *TAServerUpdate {
	mutation := newTAServerMutation(c.config, OpUpdate)
	return &TAServerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TAServerClient) UpdateOne(ts *TAServer) *TAServerUpdateOne {
	mutation := newTAServerMutation(c.config, OpUpdateOne, withTAServer(ts))
	return &TAServerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TAServerClient) UpdateOneID(id int) *TAServerUpdateOne {
	mutation := newTAServerMutation(c.config, OpUpdateOne, withTAServerID(id))
	return &TAServerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TAServer.
func (c *TAServerClient) Delete() *TAServerDelete {
	mutation := newTAServerMutation(c.config, OpDelete)
	return &TAServerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TAServerClient) DeleteOne(ts *TAServer) *TAServerDeleteOne {
	return c.DeleteOneID(ts.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TAServerClient) DeleteOneID(id int) *TAServerDeleteOne {
	builder := c.Delete().Where(taserver.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TAServerDeleteOne{builder}
}

// Query returns a query builder for TAServer.
func (c *TAServerClient) Query() *TAServerQuery {
	return &TAServerQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTAServer},
		inters: c.Interceptors(),
	}
}

// Get returns a TAServer entity by its id.
func (c *TAServerClient) Get(ctx context.Context, id int) (*TAServer, error) {
	return c.Query().Where(taserver.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TAServerClient) GetX(ctx context.Context, id int) *TAServer {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTa queries the ta edge of a TAServer.
func (c *TAServerClient) QueryTa(ts *TAServer) *TAQuery {
	query := (&TAClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ts.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(taserver.Table, taserver.FieldID, id),
			sqlgraph.To(ta.Table, ta.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, taserver.TaTable, taserver.TaColumn),
		)
		fromV = sqlgraph.Neighbors(ts.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryService queries the service edge of a TAServer.
func (c *TAServerClient) QueryService(ts *TAServer) *ServiceQuery {
	query := (&ServiceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ts.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(taserver.Table, taserver.FieldID, id),
			sqlgraph.To(service.Table, service.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, taserver.ServiceTable, taserver.ServiceColumn),
		)
		fromV = sqlgraph.Neighbors(ts.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TAServerClient) Hooks() []Hook {
	return c.hooks.TAServer
}

// Interceptors returns the client interceptors.
func (c *TAServerClient) Interceptors() []Interceptor {
	return c.inters.TAServer
}

func (c *TAServerClient) mutate(ctx context.Context, m *TAServerMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TAServerCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TAServerUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TAServerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TAServerDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TAServer mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		CTAudit, Service, TA, TACode, TAServer []ent.Hook
	}
	inters struct {
		CTAudit, Service, TA, TACode, TAServer []ent.Interceptor
	}
)
