// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/akakou/ra_webs/ttp/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/akakou/ra_webs/ttp/ent/ctlog"
	"github.com/akakou/ra_webs/ttp/ent/tainfo"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CTLog is the client for interacting with the CTLog builders.
	CTLog *CTLogClient
	// TAInfo is the client for interacting with the TAInfo builders.
	TAInfo *TAInfoClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CTLog = NewCTLogClient(c.config)
	c.TAInfo = NewTAInfoClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		CTLog:  NewCTLogClient(cfg),
		TAInfo: NewTAInfoClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		CTLog:  NewCTLogClient(cfg),
		TAInfo: NewTAInfoClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CTLog.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.CTLog.Use(hooks...)
	c.TAInfo.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.CTLog.Intercept(interceptors...)
	c.TAInfo.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CTLogMutation:
		return c.CTLog.mutate(ctx, m)
	case *TAInfoMutation:
		return c.TAInfo.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CTLogClient is a client for the CTLog schema.
type CTLogClient struct {
	config
}

// NewCTLogClient returns a client for the CTLog from the given config.
func NewCTLogClient(c config) *CTLogClient {
	return &CTLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ctlog.Hooks(f(g(h())))`.
func (c *CTLogClient) Use(hooks ...Hook) {
	c.hooks.CTLog = append(c.hooks.CTLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ctlog.Intercept(f(g(h())))`.
func (c *CTLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.CTLog = append(c.inters.CTLog, interceptors...)
}

// Create returns a builder for creating a CTLog entity.
func (c *CTLogClient) Create() *CTLogCreate {
	mutation := newCTLogMutation(c.config, OpCreate)
	return &CTLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CTLog entities.
func (c *CTLogClient) CreateBulk(builders ...*CTLogCreate) *CTLogCreateBulk {
	return &CTLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CTLogClient) MapCreateBulk(slice any, setFunc func(*CTLogCreate, int)) *CTLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CTLogCreateBulk{err: fmt.Errorf("calling to CTLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CTLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CTLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CTLog.
func (c *CTLogClient) Update() *CTLogUpdate {
	mutation := newCTLogMutation(c.config, OpUpdate)
	return &CTLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CTLogClient) UpdateOne(cl *CTLog) *CTLogUpdateOne {
	mutation := newCTLogMutation(c.config, OpUpdateOne, withCTLog(cl))
	return &CTLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CTLogClient) UpdateOneID(id int) *CTLogUpdateOne {
	mutation := newCTLogMutation(c.config, OpUpdateOne, withCTLogID(id))
	return &CTLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CTLog.
func (c *CTLogClient) Delete() *CTLogDelete {
	mutation := newCTLogMutation(c.config, OpDelete)
	return &CTLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CTLogClient) DeleteOne(cl *CTLog) *CTLogDeleteOne {
	return c.DeleteOneID(cl.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CTLogClient) DeleteOneID(id int) *CTLogDeleteOne {
	builder := c.Delete().Where(ctlog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CTLogDeleteOne{builder}
}

// Query returns a query builder for CTLog.
func (c *CTLogClient) Query() *CTLogQuery {
	return &CTLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCTLog},
		inters: c.Interceptors(),
	}
}

// Get returns a CTLog entity by its id.
func (c *CTLogClient) Get(ctx context.Context, id int) (*CTLog, error) {
	return c.Query().Where(ctlog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CTLogClient) GetX(ctx context.Context, id int) *CTLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTaInfo queries the ta_info edge of a CTLog.
func (c *CTLogClient) QueryTaInfo(cl *CTLog) *TAInfoQuery {
	query := (&TAInfoClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := cl.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ctlog.Table, ctlog.FieldID, id),
			sqlgraph.To(tainfo.Table, tainfo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ctlog.TaInfoTable, ctlog.TaInfoColumn),
		)
		fromV = sqlgraph.Neighbors(cl.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CTLogClient) Hooks() []Hook {
	return c.hooks.CTLog
}

// Interceptors returns the client interceptors.
func (c *CTLogClient) Interceptors() []Interceptor {
	return c.inters.CTLog
}

func (c *CTLogClient) mutate(ctx context.Context, m *CTLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CTLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CTLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CTLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CTLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CTLog mutation op: %q", m.Op())
	}
}

// TAInfoClient is a client for the TAInfo schema.
type TAInfoClient struct {
	config
}

// NewTAInfoClient returns a client for the TAInfo from the given config.
func NewTAInfoClient(c config) *TAInfoClient {
	return &TAInfoClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tainfo.Hooks(f(g(h())))`.
func (c *TAInfoClient) Use(hooks ...Hook) {
	c.hooks.TAInfo = append(c.hooks.TAInfo, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tainfo.Intercept(f(g(h())))`.
func (c *TAInfoClient) Intercept(interceptors ...Interceptor) {
	c.inters.TAInfo = append(c.inters.TAInfo, interceptors...)
}

// Create returns a builder for creating a TAInfo entity.
func (c *TAInfoClient) Create() *TAInfoCreate {
	mutation := newTAInfoMutation(c.config, OpCreate)
	return &TAInfoCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TAInfo entities.
func (c *TAInfoClient) CreateBulk(builders ...*TAInfoCreate) *TAInfoCreateBulk {
	return &TAInfoCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TAInfoClient) MapCreateBulk(slice any, setFunc func(*TAInfoCreate, int)) *TAInfoCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TAInfoCreateBulk{err: fmt.Errorf("calling to TAInfoClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TAInfoCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TAInfoCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TAInfo.
func (c *TAInfoClient) Update() *TAInfoUpdate {
	mutation := newTAInfoMutation(c.config, OpUpdate)
	return &TAInfoUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TAInfoClient) UpdateOne(ti *TAInfo) *TAInfoUpdateOne {
	mutation := newTAInfoMutation(c.config, OpUpdateOne, withTAInfo(ti))
	return &TAInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TAInfoClient) UpdateOneID(id int) *TAInfoUpdateOne {
	mutation := newTAInfoMutation(c.config, OpUpdateOne, withTAInfoID(id))
	return &TAInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TAInfo.
func (c *TAInfoClient) Delete() *TAInfoDelete {
	mutation := newTAInfoMutation(c.config, OpDelete)
	return &TAInfoDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TAInfoClient) DeleteOne(ti *TAInfo) *TAInfoDeleteOne {
	return c.DeleteOneID(ti.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TAInfoClient) DeleteOneID(id int) *TAInfoDeleteOne {
	builder := c.Delete().Where(tainfo.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TAInfoDeleteOne{builder}
}

// Query returns a query builder for TAInfo.
func (c *TAInfoClient) Query() *TAInfoQuery {
	return &TAInfoQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTAInfo},
		inters: c.Interceptors(),
	}
}

// Get returns a TAInfo entity by its id.
func (c *TAInfoClient) Get(ctx context.Context, id int) (*TAInfo, error) {
	return c.Query().Where(tainfo.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TAInfoClient) GetX(ctx context.Context, id int) *TAInfo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCtLog queries the ct_log edge of a TAInfo.
func (c *TAInfoClient) QueryCtLog(ti *TAInfo) *CTLogQuery {
	query := (&CTLogClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ti.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tainfo.Table, tainfo.FieldID, id),
			sqlgraph.To(ctlog.Table, ctlog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, tainfo.CtLogTable, tainfo.CtLogColumn),
		)
		fromV = sqlgraph.Neighbors(ti.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TAInfoClient) Hooks() []Hook {
	return c.hooks.TAInfo
}

// Interceptors returns the client interceptors.
func (c *TAInfoClient) Interceptors() []Interceptor {
	return c.inters.TAInfo
}

func (c *TAInfoClient) mutate(ctx context.Context, m *TAInfoMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TAInfoCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TAInfoUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TAInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TAInfoDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TAInfo mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		CTLog, TAInfo []ent.Hook
	}
	inters struct {
		CTLog, TAInfo []ent.Interceptor
	}
)
