// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/ra_webs/ttp/ent/ctaudit"
	"github.com/akakou/ra_webs/ttp/ent/predicate"
	"github.com/akakou/ra_webs/ttp/ent/ta"
)

// CTAuditUpdate is the builder for updating CTAudit entities.
type CTAuditUpdate struct {
	config
	hooks    []Hook
	mutation *CTAuditMutation
}

// Where appends a list predicates to the CTAuditUpdate builder.
func (cau *CTAuditUpdate) Where(ps ...predicate.CTAudit) *CTAuditUpdate {
	cau.mutation.Where(ps...)
	return cau
}

// SetCtValid sets the "ct_valid" field.
func (cau *CTAuditUpdate) SetCtValid(b bool) *CTAuditUpdate {
	cau.mutation.SetCtValid(b)
	return cau
}

// SetNillableCtValid sets the "ct_valid" field if the given value is not nil.
func (cau *CTAuditUpdate) SetNillableCtValid(b *bool) *CTAuditUpdate {
	if b != nil {
		cau.SetCtValid(*b)
	}
	return cau
}

// SetLastCt sets the "last_ct" field.
func (cau *CTAuditUpdate) SetLastCt(s string) *CTAuditUpdate {
	cau.mutation.SetLastCt(s)
	return cau
}

// SetNillableLastCt sets the "last_ct" field if the given value is not nil.
func (cau *CTAuditUpdate) SetNillableLastCt(s *string) *CTAuditUpdate {
	if s != nil {
		cau.SetLastCt(*s)
	}
	return cau
}

// AddTumIDs adds the "ta" edge to the TA entity by IDs.
func (cau *CTAuditUpdate) AddTumIDs(ids ...int) *CTAuditUpdate {
	cau.mutation.AddTumIDs(ids...)
	return cau
}

// AddTa adds the "ta" edges to the TA entity.
func (cau *CTAuditUpdate) AddTa(t ...*TA) *CTAuditUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return cau.AddTumIDs(ids...)
}

// Mutation returns the CTAuditMutation object of the builder.
func (cau *CTAuditUpdate) Mutation() *CTAuditMutation {
	return cau.mutation
}

// ClearTa clears all "ta" edges to the TA entity.
func (cau *CTAuditUpdate) ClearTa() *CTAuditUpdate {
	cau.mutation.ClearTa()
	return cau
}

// RemoveTumIDs removes the "ta" edge to TA entities by IDs.
func (cau *CTAuditUpdate) RemoveTumIDs(ids ...int) *CTAuditUpdate {
	cau.mutation.RemoveTumIDs(ids...)
	return cau
}

// RemoveTa removes "ta" edges to TA entities.
func (cau *CTAuditUpdate) RemoveTa(t ...*TA) *CTAuditUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return cau.RemoveTumIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cau *CTAuditUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cau.sqlSave, cau.mutation, cau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cau *CTAuditUpdate) SaveX(ctx context.Context) int {
	affected, err := cau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cau *CTAuditUpdate) Exec(ctx context.Context) error {
	_, err := cau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cau *CTAuditUpdate) ExecX(ctx context.Context) {
	if err := cau.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cau *CTAuditUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(ctaudit.Table, ctaudit.Columns, sqlgraph.NewFieldSpec(ctaudit.FieldID, field.TypeInt))
	if ps := cau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cau.mutation.CtValid(); ok {
		_spec.SetField(ctaudit.FieldCtValid, field.TypeBool, value)
	}
	if value, ok := cau.mutation.LastCt(); ok {
		_spec.SetField(ctaudit.FieldLastCt, field.TypeString, value)
	}
	if cau.mutation.TaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   ctaudit.TaTable,
			Columns: []string{ctaudit.TaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ta.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cau.mutation.RemovedTaIDs(); len(nodes) > 0 && !cau.mutation.TaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   ctaudit.TaTable,
			Columns: []string{ctaudit.TaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cau.mutation.TaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   ctaudit.TaTable,
			Columns: []string{ctaudit.TaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ctaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cau.mutation.done = true
	return n, nil
}

// CTAuditUpdateOne is the builder for updating a single CTAudit entity.
type CTAuditUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CTAuditMutation
}

// SetCtValid sets the "ct_valid" field.
func (cauo *CTAuditUpdateOne) SetCtValid(b bool) *CTAuditUpdateOne {
	cauo.mutation.SetCtValid(b)
	return cauo
}

// SetNillableCtValid sets the "ct_valid" field if the given value is not nil.
func (cauo *CTAuditUpdateOne) SetNillableCtValid(b *bool) *CTAuditUpdateOne {
	if b != nil {
		cauo.SetCtValid(*b)
	}
	return cauo
}

// SetLastCt sets the "last_ct" field.
func (cauo *CTAuditUpdateOne) SetLastCt(s string) *CTAuditUpdateOne {
	cauo.mutation.SetLastCt(s)
	return cauo
}

// SetNillableLastCt sets the "last_ct" field if the given value is not nil.
func (cauo *CTAuditUpdateOne) SetNillableLastCt(s *string) *CTAuditUpdateOne {
	if s != nil {
		cauo.SetLastCt(*s)
	}
	return cauo
}

// AddTumIDs adds the "ta" edge to the TA entity by IDs.
func (cauo *CTAuditUpdateOne) AddTumIDs(ids ...int) *CTAuditUpdateOne {
	cauo.mutation.AddTumIDs(ids...)
	return cauo
}

// AddTa adds the "ta" edges to the TA entity.
func (cauo *CTAuditUpdateOne) AddTa(t ...*TA) *CTAuditUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return cauo.AddTumIDs(ids...)
}

// Mutation returns the CTAuditMutation object of the builder.
func (cauo *CTAuditUpdateOne) Mutation() *CTAuditMutation {
	return cauo.mutation
}

// ClearTa clears all "ta" edges to the TA entity.
func (cauo *CTAuditUpdateOne) ClearTa() *CTAuditUpdateOne {
	cauo.mutation.ClearTa()
	return cauo
}

// RemoveTumIDs removes the "ta" edge to TA entities by IDs.
func (cauo *CTAuditUpdateOne) RemoveTumIDs(ids ...int) *CTAuditUpdateOne {
	cauo.mutation.RemoveTumIDs(ids...)
	return cauo
}

// RemoveTa removes "ta" edges to TA entities.
func (cauo *CTAuditUpdateOne) RemoveTa(t ...*TA) *CTAuditUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return cauo.RemoveTumIDs(ids...)
}

// Where appends a list predicates to the CTAuditUpdate builder.
func (cauo *CTAuditUpdateOne) Where(ps ...predicate.CTAudit) *CTAuditUpdateOne {
	cauo.mutation.Where(ps...)
	return cauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cauo *CTAuditUpdateOne) Select(field string, fields ...string) *CTAuditUpdateOne {
	cauo.fields = append([]string{field}, fields...)
	return cauo
}

// Save executes the query and returns the updated CTAudit entity.
func (cauo *CTAuditUpdateOne) Save(ctx context.Context) (*CTAudit, error) {
	return withHooks(ctx, cauo.sqlSave, cauo.mutation, cauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cauo *CTAuditUpdateOne) SaveX(ctx context.Context) *CTAudit {
	node, err := cauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cauo *CTAuditUpdateOne) Exec(ctx context.Context) error {
	_, err := cauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cauo *CTAuditUpdateOne) ExecX(ctx context.Context) {
	if err := cauo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cauo *CTAuditUpdateOne) sqlSave(ctx context.Context) (_node *CTAudit, err error) {
	_spec := sqlgraph.NewUpdateSpec(ctaudit.Table, ctaudit.Columns, sqlgraph.NewFieldSpec(ctaudit.FieldID, field.TypeInt))
	id, ok := cauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CTAudit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ctaudit.FieldID)
		for _, f := range fields {
			if !ctaudit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ctaudit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cauo.mutation.CtValid(); ok {
		_spec.SetField(ctaudit.FieldCtValid, field.TypeBool, value)
	}
	if value, ok := cauo.mutation.LastCt(); ok {
		_spec.SetField(ctaudit.FieldLastCt, field.TypeString, value)
	}
	if cauo.mutation.TaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   ctaudit.TaTable,
			Columns: []string{ctaudit.TaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ta.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cauo.mutation.RemovedTaIDs(); len(nodes) > 0 && !cauo.mutation.TaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   ctaudit.TaTable,
			Columns: []string{ctaudit.TaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cauo.mutation.TaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   ctaudit.TaTable,
			Columns: []string{ctaudit.TaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CTAudit{config: cauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ctaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cauo.mutation.done = true
	return _node, nil
}
