// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/ra_webs/ttp/ent/ctlogaudit"
	"github.com/akakou/ra_webs/ttp/ent/predicate"
	"github.com/akakou/ra_webs/ttp/ent/tainfo"
)

// CTLogAuditUpdate is the builder for updating CTLogAudit entities.
type CTLogAuditUpdate struct {
	config
	hooks    []Hook
	mutation *CTLogAuditMutation
}

// Where appends a list predicates to the CTLogAuditUpdate builder.
func (clau *CTLogAuditUpdate) Where(ps ...predicate.CTLogAudit) *CTLogAuditUpdate {
	clau.mutation.Where(ps...)
	return clau
}

// SetIsValid sets the "is_valid" field.
func (clau *CTLogAuditUpdate) SetIsValid(b bool) *CTLogAuditUpdate {
	clau.mutation.SetIsValid(b)
	return clau
}

// SetNillableIsValid sets the "is_valid" field if the given value is not nil.
func (clau *CTLogAuditUpdate) SetNillableIsValid(b *bool) *CTLogAuditUpdate {
	if b != nil {
		clau.SetIsValid(*b)
	}
	return clau
}

// SetLatestCtID sets the "latest_ct_id" field.
func (clau *CTLogAuditUpdate) SetLatestCtID(s string) *CTLogAuditUpdate {
	clau.mutation.SetLatestCtID(s)
	return clau
}

// SetNillableLatestCtID sets the "latest_ct_id" field if the given value is not nil.
func (clau *CTLogAuditUpdate) SetNillableLatestCtID(s *string) *CTLogAuditUpdate {
	if s != nil {
		clau.SetLatestCtID(*s)
	}
	return clau
}

// SetTaInfoID sets the "ta_info" edge to the TAInfo entity by ID.
func (clau *CTLogAuditUpdate) SetTaInfoID(id int) *CTLogAuditUpdate {
	clau.mutation.SetTaInfoID(id)
	return clau
}

// SetNillableTaInfoID sets the "ta_info" edge to the TAInfo entity by ID if the given value is not nil.
func (clau *CTLogAuditUpdate) SetNillableTaInfoID(id *int) *CTLogAuditUpdate {
	if id != nil {
		clau = clau.SetTaInfoID(*id)
	}
	return clau
}

// SetTaInfo sets the "ta_info" edge to the TAInfo entity.
func (clau *CTLogAuditUpdate) SetTaInfo(t *TAInfo) *CTLogAuditUpdate {
	return clau.SetTaInfoID(t.ID)
}

// Mutation returns the CTLogAuditMutation object of the builder.
func (clau *CTLogAuditUpdate) Mutation() *CTLogAuditMutation {
	return clau.mutation
}

// ClearTaInfo clears the "ta_info" edge to the TAInfo entity.
func (clau *CTLogAuditUpdate) ClearTaInfo() *CTLogAuditUpdate {
	clau.mutation.ClearTaInfo()
	return clau
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (clau *CTLogAuditUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, clau.sqlSave, clau.mutation, clau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (clau *CTLogAuditUpdate) SaveX(ctx context.Context) int {
	affected, err := clau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (clau *CTLogAuditUpdate) Exec(ctx context.Context) error {
	_, err := clau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (clau *CTLogAuditUpdate) ExecX(ctx context.Context) {
	if err := clau.Exec(ctx); err != nil {
		panic(err)
	}
}

func (clau *CTLogAuditUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(ctlogaudit.Table, ctlogaudit.Columns, sqlgraph.NewFieldSpec(ctlogaudit.FieldID, field.TypeInt))
	if ps := clau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := clau.mutation.IsValid(); ok {
		_spec.SetField(ctlogaudit.FieldIsValid, field.TypeBool, value)
	}
	if value, ok := clau.mutation.LatestCtID(); ok {
		_spec.SetField(ctlogaudit.FieldLatestCtID, field.TypeString, value)
	}
	if clau.mutation.TaInfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   ctlogaudit.TaInfoTable,
			Columns: []string{ctlogaudit.TaInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tainfo.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := clau.mutation.TaInfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   ctlogaudit.TaInfoTable,
			Columns: []string{ctlogaudit.TaInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tainfo.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, clau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ctlogaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	clau.mutation.done = true
	return n, nil
}

// CTLogAuditUpdateOne is the builder for updating a single CTLogAudit entity.
type CTLogAuditUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CTLogAuditMutation
}

// SetIsValid sets the "is_valid" field.
func (clauo *CTLogAuditUpdateOne) SetIsValid(b bool) *CTLogAuditUpdateOne {
	clauo.mutation.SetIsValid(b)
	return clauo
}

// SetNillableIsValid sets the "is_valid" field if the given value is not nil.
func (clauo *CTLogAuditUpdateOne) SetNillableIsValid(b *bool) *CTLogAuditUpdateOne {
	if b != nil {
		clauo.SetIsValid(*b)
	}
	return clauo
}

// SetLatestCtID sets the "latest_ct_id" field.
func (clauo *CTLogAuditUpdateOne) SetLatestCtID(s string) *CTLogAuditUpdateOne {
	clauo.mutation.SetLatestCtID(s)
	return clauo
}

// SetNillableLatestCtID sets the "latest_ct_id" field if the given value is not nil.
func (clauo *CTLogAuditUpdateOne) SetNillableLatestCtID(s *string) *CTLogAuditUpdateOne {
	if s != nil {
		clauo.SetLatestCtID(*s)
	}
	return clauo
}

// SetTaInfoID sets the "ta_info" edge to the TAInfo entity by ID.
func (clauo *CTLogAuditUpdateOne) SetTaInfoID(id int) *CTLogAuditUpdateOne {
	clauo.mutation.SetTaInfoID(id)
	return clauo
}

// SetNillableTaInfoID sets the "ta_info" edge to the TAInfo entity by ID if the given value is not nil.
func (clauo *CTLogAuditUpdateOne) SetNillableTaInfoID(id *int) *CTLogAuditUpdateOne {
	if id != nil {
		clauo = clauo.SetTaInfoID(*id)
	}
	return clauo
}

// SetTaInfo sets the "ta_info" edge to the TAInfo entity.
func (clauo *CTLogAuditUpdateOne) SetTaInfo(t *TAInfo) *CTLogAuditUpdateOne {
	return clauo.SetTaInfoID(t.ID)
}

// Mutation returns the CTLogAuditMutation object of the builder.
func (clauo *CTLogAuditUpdateOne) Mutation() *CTLogAuditMutation {
	return clauo.mutation
}

// ClearTaInfo clears the "ta_info" edge to the TAInfo entity.
func (clauo *CTLogAuditUpdateOne) ClearTaInfo() *CTLogAuditUpdateOne {
	clauo.mutation.ClearTaInfo()
	return clauo
}

// Where appends a list predicates to the CTLogAuditUpdate builder.
func (clauo *CTLogAuditUpdateOne) Where(ps ...predicate.CTLogAudit) *CTLogAuditUpdateOne {
	clauo.mutation.Where(ps...)
	return clauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (clauo *CTLogAuditUpdateOne) Select(field string, fields ...string) *CTLogAuditUpdateOne {
	clauo.fields = append([]string{field}, fields...)
	return clauo
}

// Save executes the query and returns the updated CTLogAudit entity.
func (clauo *CTLogAuditUpdateOne) Save(ctx context.Context) (*CTLogAudit, error) {
	return withHooks(ctx, clauo.sqlSave, clauo.mutation, clauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (clauo *CTLogAuditUpdateOne) SaveX(ctx context.Context) *CTLogAudit {
	node, err := clauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (clauo *CTLogAuditUpdateOne) Exec(ctx context.Context) error {
	_, err := clauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (clauo *CTLogAuditUpdateOne) ExecX(ctx context.Context) {
	if err := clauo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (clauo *CTLogAuditUpdateOne) sqlSave(ctx context.Context) (_node *CTLogAudit, err error) {
	_spec := sqlgraph.NewUpdateSpec(ctlogaudit.Table, ctlogaudit.Columns, sqlgraph.NewFieldSpec(ctlogaudit.FieldID, field.TypeInt))
	id, ok := clauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CTLogAudit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := clauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ctlogaudit.FieldID)
		for _, f := range fields {
			if !ctlogaudit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ctlogaudit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := clauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := clauo.mutation.IsValid(); ok {
		_spec.SetField(ctlogaudit.FieldIsValid, field.TypeBool, value)
	}
	if value, ok := clauo.mutation.LatestCtID(); ok {
		_spec.SetField(ctlogaudit.FieldLatestCtID, field.TypeString, value)
	}
	if clauo.mutation.TaInfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   ctlogaudit.TaInfoTable,
			Columns: []string{ctlogaudit.TaInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tainfo.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := clauo.mutation.TaInfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   ctlogaudit.TaInfoTable,
			Columns: []string{ctlogaudit.TaInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tainfo.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CTLogAudit{config: clauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, clauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ctlogaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	clauo.mutation.done = true
	return _node, nil
}
