// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/ra_webs/ttp/ent/ctlogaudit"
	"github.com/akakou/ra_webs/ttp/ent/tainfo"
)

// CTLogAudit is the model entity for the CTLogAudit schema.
type CTLogAudit struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// IsValid holds the value of the "is_valid" field.
	IsValid bool `json:"is_valid,omitempty"`
	// LatestCtID holds the value of the "latest_ct_id" field.
	LatestCtID string `json:"latest_ct_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CTLogAuditQuery when eager-loading is set.
	Edges        CTLogAuditEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CTLogAuditEdges holds the relations/edges for other nodes in the graph.
type CTLogAuditEdges struct {
	// TaInfo holds the value of the ta_info edge.
	TaInfo *TAInfo `json:"ta_info,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaInfoOrErr returns the TaInfo value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CTLogAuditEdges) TaInfoOrErr() (*TAInfo, error) {
	if e.loadedTypes[0] {
		if e.TaInfo == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: tainfo.Label}
		}
		return e.TaInfo, nil
	}
	return nil, &NotLoadedError{edge: "ta_info"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CTLogAudit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ctlogaudit.FieldIsValid:
			values[i] = new(sql.NullBool)
		case ctlogaudit.FieldID:
			values[i] = new(sql.NullInt64)
		case ctlogaudit.FieldLatestCtID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CTLogAudit fields.
func (cla *CTLogAudit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ctlogaudit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cla.ID = int(value.Int64)
		case ctlogaudit.FieldIsValid:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_valid", values[i])
			} else if value.Valid {
				cla.IsValid = value.Bool
			}
		case ctlogaudit.FieldLatestCtID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field latest_ct_id", values[i])
			} else if value.Valid {
				cla.LatestCtID = value.String
			}
		default:
			cla.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CTLogAudit.
// This includes values selected through modifiers, order, etc.
func (cla *CTLogAudit) Value(name string) (ent.Value, error) {
	return cla.selectValues.Get(name)
}

// QueryTaInfo queries the "ta_info" edge of the CTLogAudit entity.
func (cla *CTLogAudit) QueryTaInfo() *TAInfoQuery {
	return NewCTLogAuditClient(cla.config).QueryTaInfo(cla)
}

// Update returns a builder for updating this CTLogAudit.
// Note that you need to call CTLogAudit.Unwrap() before calling this method if this CTLogAudit
// was returned from a transaction, and the transaction was committed or rolled back.
func (cla *CTLogAudit) Update() *CTLogAuditUpdateOne {
	return NewCTLogAuditClient(cla.config).UpdateOne(cla)
}

// Unwrap unwraps the CTLogAudit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cla *CTLogAudit) Unwrap() *CTLogAudit {
	_tx, ok := cla.config.driver.(*txDriver)
	if !ok {
		panic("ent: CTLogAudit is not a transactional entity")
	}
	cla.config.driver = _tx.drv
	return cla
}

// String implements the fmt.Stringer.
func (cla *CTLogAudit) String() string {
	var builder strings.Builder
	builder.WriteString("CTLogAudit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cla.ID))
	builder.WriteString("is_valid=")
	builder.WriteString(fmt.Sprintf("%v", cla.IsValid))
	builder.WriteString(", ")
	builder.WriteString("latest_ct_id=")
	builder.WriteString(cla.LatestCtID)
	builder.WriteByte(')')
	return builder.String()
}

// CTLogAudits is a parsable slice of CTLogAudit.
type CTLogAudits []*CTLogAudit
