// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/ra_webs/ttp/ent/ctlog"
	"github.com/akakou/ra_webs/ttp/ent/predicate"
	"github.com/akakou/ra_webs/ttp/ent/tainfo"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeCTLog  = "CTLog"
	TypeTAInfo = "TAInfo"
)

// CTLogMutation represents an operation that mutates the CTLog nodes in the graph.
type CTLogMutation struct {
	config
	op             Op
	typ            string
	id             *int
	domain         *string
	public_key     *[]byte
	clearedFields  map[string]struct{}
	ta_info        *int
	clearedta_info bool
	done           bool
	oldValue       func(context.Context) (*CTLog, error)
	predicates     []predicate.CTLog
}

var _ ent.Mutation = (*CTLogMutation)(nil)

// ctlogOption allows management of the mutation configuration using functional options.
type ctlogOption func(*CTLogMutation)

// newCTLogMutation creates new mutation for the CTLog entity.
func newCTLogMutation(c config, op Op, opts ...ctlogOption) *CTLogMutation {
	m := &CTLogMutation{
		config:        c,
		op:            op,
		typ:           TypeCTLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCTLogID sets the ID field of the mutation.
func withCTLogID(id int) ctlogOption {
	return func(m *CTLogMutation) {
		var (
			err   error
			once  sync.Once
			value *CTLog
		)
		m.oldValue = func(ctx context.Context) (*CTLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().CTLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCTLog sets the old CTLog of the mutation.
func withCTLog(node *CTLog) ctlogOption {
	return func(m *CTLogMutation) {
		m.oldValue = func(context.Context) (*CTLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CTLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CTLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CTLogMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *CTLogMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().CTLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetDomain sets the "domain" field.
func (m *CTLogMutation) SetDomain(s string) {
	m.domain = &s
}

// Domain returns the value of the "domain" field in the mutation.
func (m *CTLogMutation) Domain() (r string, exists bool) {
	v := m.domain
	if v == nil {
		return
	}
	return *v, true
}

// OldDomain returns the old "domain" field's value of the CTLog entity.
// If the CTLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CTLogMutation) OldDomain(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDomain is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDomain requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDomain: %w", err)
	}
	return oldValue.Domain, nil
}

// ResetDomain resets all changes to the "domain" field.
func (m *CTLogMutation) ResetDomain() {
	m.domain = nil
}

// SetPublicKey sets the "public_key" field.
func (m *CTLogMutation) SetPublicKey(b []byte) {
	m.public_key = &b
}

// PublicKey returns the value of the "public_key" field in the mutation.
func (m *CTLogMutation) PublicKey() (r []byte, exists bool) {
	v := m.public_key
	if v == nil {
		return
	}
	return *v, true
}

// OldPublicKey returns the old "public_key" field's value of the CTLog entity.
// If the CTLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CTLogMutation) OldPublicKey(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPublicKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPublicKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPublicKey: %w", err)
	}
	return oldValue.PublicKey, nil
}

// ResetPublicKey resets all changes to the "public_key" field.
func (m *CTLogMutation) ResetPublicKey() {
	m.public_key = nil
}

// SetTaInfoID sets the "ta_info" edge to the TAInfo entity by id.
func (m *CTLogMutation) SetTaInfoID(id int) {
	m.ta_info = &id
}

// ClearTaInfo clears the "ta_info" edge to the TAInfo entity.
func (m *CTLogMutation) ClearTaInfo() {
	m.clearedta_info = true
}

// TaInfoCleared reports if the "ta_info" edge to the TAInfo entity was cleared.
func (m *CTLogMutation) TaInfoCleared() bool {
	return m.clearedta_info
}

// TaInfoID returns the "ta_info" edge ID in the mutation.
func (m *CTLogMutation) TaInfoID() (id int, exists bool) {
	if m.ta_info != nil {
		return *m.ta_info, true
	}
	return
}

// TaInfoIDs returns the "ta_info" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// TaInfoID instead. It exists only for internal usage by the builders.
func (m *CTLogMutation) TaInfoIDs() (ids []int) {
	if id := m.ta_info; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetTaInfo resets all changes to the "ta_info" edge.
func (m *CTLogMutation) ResetTaInfo() {
	m.ta_info = nil
	m.clearedta_info = false
}

// Where appends a list predicates to the CTLogMutation builder.
func (m *CTLogMutation) Where(ps ...predicate.CTLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the CTLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *CTLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.CTLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *CTLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CTLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (CTLog).
func (m *CTLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CTLogMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.domain != nil {
		fields = append(fields, ctlog.FieldDomain)
	}
	if m.public_key != nil {
		fields = append(fields, ctlog.FieldPublicKey)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CTLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case ctlog.FieldDomain:
		return m.Domain()
	case ctlog.FieldPublicKey:
		return m.PublicKey()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CTLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case ctlog.FieldDomain:
		return m.OldDomain(ctx)
	case ctlog.FieldPublicKey:
		return m.OldPublicKey(ctx)
	}
	return nil, fmt.Errorf("unknown CTLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CTLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case ctlog.FieldDomain:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDomain(v)
		return nil
	case ctlog.FieldPublicKey:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPublicKey(v)
		return nil
	}
	return fmt.Errorf("unknown CTLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CTLogMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CTLogMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CTLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown CTLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CTLogMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CTLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CTLogMutation) ClearField(name string) error {
	return fmt.Errorf("unknown CTLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CTLogMutation) ResetField(name string) error {
	switch name {
	case ctlog.FieldDomain:
		m.ResetDomain()
		return nil
	case ctlog.FieldPublicKey:
		m.ResetPublicKey()
		return nil
	}
	return fmt.Errorf("unknown CTLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CTLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.ta_info != nil {
		edges = append(edges, ctlog.EdgeTaInfo)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CTLogMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case ctlog.EdgeTaInfo:
		if id := m.ta_info; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CTLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CTLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CTLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedta_info {
		edges = append(edges, ctlog.EdgeTaInfo)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CTLogMutation) EdgeCleared(name string) bool {
	switch name {
	case ctlog.EdgeTaInfo:
		return m.clearedta_info
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CTLogMutation) ClearEdge(name string) error {
	switch name {
	case ctlog.EdgeTaInfo:
		m.ClearTaInfo()
		return nil
	}
	return fmt.Errorf("unknown CTLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CTLogMutation) ResetEdge(name string) error {
	switch name {
	case ctlog.EdgeTaInfo:
		m.ResetTaInfo()
		return nil
	}
	return fmt.Errorf("unknown CTLog edge %s", name)
}

// TAInfoMutation represents an operation that mutates the TAInfo nodes in the graph.
type TAInfoMutation struct {
	config
	op            Op
	typ           string
	id            *int
	domain        *string
	public_key    *[]byte
	attestation   *string
	clearedFields map[string]struct{}
	ct_log        map[int]struct{}
	removedct_log map[int]struct{}
	clearedct_log bool
	done          bool
	oldValue      func(context.Context) (*TAInfo, error)
	predicates    []predicate.TAInfo
}

var _ ent.Mutation = (*TAInfoMutation)(nil)

// tainfoOption allows management of the mutation configuration using functional options.
type tainfoOption func(*TAInfoMutation)

// newTAInfoMutation creates new mutation for the TAInfo entity.
func newTAInfoMutation(c config, op Op, opts ...tainfoOption) *TAInfoMutation {
	m := &TAInfoMutation{
		config:        c,
		op:            op,
		typ:           TypeTAInfo,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTAInfoID sets the ID field of the mutation.
func withTAInfoID(id int) tainfoOption {
	return func(m *TAInfoMutation) {
		var (
			err   error
			once  sync.Once
			value *TAInfo
		)
		m.oldValue = func(ctx context.Context) (*TAInfo, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TAInfo.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTAInfo sets the old TAInfo of the mutation.
func withTAInfo(node *TAInfo) tainfoOption {
	return func(m *TAInfoMutation) {
		m.oldValue = func(context.Context) (*TAInfo, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TAInfoMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TAInfoMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TAInfoMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TAInfoMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TAInfo.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetDomain sets the "domain" field.
func (m *TAInfoMutation) SetDomain(s string) {
	m.domain = &s
}

// Domain returns the value of the "domain" field in the mutation.
func (m *TAInfoMutation) Domain() (r string, exists bool) {
	v := m.domain
	if v == nil {
		return
	}
	return *v, true
}

// OldDomain returns the old "domain" field's value of the TAInfo entity.
// If the TAInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TAInfoMutation) OldDomain(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDomain is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDomain requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDomain: %w", err)
	}
	return oldValue.Domain, nil
}

// ResetDomain resets all changes to the "domain" field.
func (m *TAInfoMutation) ResetDomain() {
	m.domain = nil
}

// SetPublicKey sets the "public_key" field.
func (m *TAInfoMutation) SetPublicKey(b []byte) {
	m.public_key = &b
}

// PublicKey returns the value of the "public_key" field in the mutation.
func (m *TAInfoMutation) PublicKey() (r []byte, exists bool) {
	v := m.public_key
	if v == nil {
		return
	}
	return *v, true
}

// OldPublicKey returns the old "public_key" field's value of the TAInfo entity.
// If the TAInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TAInfoMutation) OldPublicKey(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPublicKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPublicKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPublicKey: %w", err)
	}
	return oldValue.PublicKey, nil
}

// ResetPublicKey resets all changes to the "public_key" field.
func (m *TAInfoMutation) ResetPublicKey() {
	m.public_key = nil
}

// SetAttestation sets the "attestation" field.
func (m *TAInfoMutation) SetAttestation(s string) {
	m.attestation = &s
}

// Attestation returns the value of the "attestation" field in the mutation.
func (m *TAInfoMutation) Attestation() (r string, exists bool) {
	v := m.attestation
	if v == nil {
		return
	}
	return *v, true
}

// OldAttestation returns the old "attestation" field's value of the TAInfo entity.
// If the TAInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TAInfoMutation) OldAttestation(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAttestation is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAttestation requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAttestation: %w", err)
	}
	return oldValue.Attestation, nil
}

// ResetAttestation resets all changes to the "attestation" field.
func (m *TAInfoMutation) ResetAttestation() {
	m.attestation = nil
}

// AddCtLogIDs adds the "ct_log" edge to the CTLog entity by ids.
func (m *TAInfoMutation) AddCtLogIDs(ids ...int) {
	if m.ct_log == nil {
		m.ct_log = make(map[int]struct{})
	}
	for i := range ids {
		m.ct_log[ids[i]] = struct{}{}
	}
}

// ClearCtLog clears the "ct_log" edge to the CTLog entity.
func (m *TAInfoMutation) ClearCtLog() {
	m.clearedct_log = true
}

// CtLogCleared reports if the "ct_log" edge to the CTLog entity was cleared.
func (m *TAInfoMutation) CtLogCleared() bool {
	return m.clearedct_log
}

// RemoveCtLogIDs removes the "ct_log" edge to the CTLog entity by IDs.
func (m *TAInfoMutation) RemoveCtLogIDs(ids ...int) {
	if m.removedct_log == nil {
		m.removedct_log = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.ct_log, ids[i])
		m.removedct_log[ids[i]] = struct{}{}
	}
}

// RemovedCtLog returns the removed IDs of the "ct_log" edge to the CTLog entity.
func (m *TAInfoMutation) RemovedCtLogIDs() (ids []int) {
	for id := range m.removedct_log {
		ids = append(ids, id)
	}
	return
}

// CtLogIDs returns the "ct_log" edge IDs in the mutation.
func (m *TAInfoMutation) CtLogIDs() (ids []int) {
	for id := range m.ct_log {
		ids = append(ids, id)
	}
	return
}

// ResetCtLog resets all changes to the "ct_log" edge.
func (m *TAInfoMutation) ResetCtLog() {
	m.ct_log = nil
	m.clearedct_log = false
	m.removedct_log = nil
}

// Where appends a list predicates to the TAInfoMutation builder.
func (m *TAInfoMutation) Where(ps ...predicate.TAInfo) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TAInfoMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TAInfoMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TAInfo, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TAInfoMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TAInfoMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TAInfo).
func (m *TAInfoMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TAInfoMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.domain != nil {
		fields = append(fields, tainfo.FieldDomain)
	}
	if m.public_key != nil {
		fields = append(fields, tainfo.FieldPublicKey)
	}
	if m.attestation != nil {
		fields = append(fields, tainfo.FieldAttestation)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TAInfoMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case tainfo.FieldDomain:
		return m.Domain()
	case tainfo.FieldPublicKey:
		return m.PublicKey()
	case tainfo.FieldAttestation:
		return m.Attestation()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TAInfoMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case tainfo.FieldDomain:
		return m.OldDomain(ctx)
	case tainfo.FieldPublicKey:
		return m.OldPublicKey(ctx)
	case tainfo.FieldAttestation:
		return m.OldAttestation(ctx)
	}
	return nil, fmt.Errorf("unknown TAInfo field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TAInfoMutation) SetField(name string, value ent.Value) error {
	switch name {
	case tainfo.FieldDomain:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDomain(v)
		return nil
	case tainfo.FieldPublicKey:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPublicKey(v)
		return nil
	case tainfo.FieldAttestation:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAttestation(v)
		return nil
	}
	return fmt.Errorf("unknown TAInfo field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TAInfoMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TAInfoMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TAInfoMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown TAInfo numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TAInfoMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TAInfoMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TAInfoMutation) ClearField(name string) error {
	return fmt.Errorf("unknown TAInfo nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TAInfoMutation) ResetField(name string) error {
	switch name {
	case tainfo.FieldDomain:
		m.ResetDomain()
		return nil
	case tainfo.FieldPublicKey:
		m.ResetPublicKey()
		return nil
	case tainfo.FieldAttestation:
		m.ResetAttestation()
		return nil
	}
	return fmt.Errorf("unknown TAInfo field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TAInfoMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.ct_log != nil {
		edges = append(edges, tainfo.EdgeCtLog)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TAInfoMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case tainfo.EdgeCtLog:
		ids := make([]ent.Value, 0, len(m.ct_log))
		for id := range m.ct_log {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TAInfoMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedct_log != nil {
		edges = append(edges, tainfo.EdgeCtLog)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TAInfoMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case tainfo.EdgeCtLog:
		ids := make([]ent.Value, 0, len(m.removedct_log))
		for id := range m.removedct_log {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TAInfoMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedct_log {
		edges = append(edges, tainfo.EdgeCtLog)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TAInfoMutation) EdgeCleared(name string) bool {
	switch name {
	case tainfo.EdgeCtLog:
		return m.clearedct_log
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TAInfoMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown TAInfo unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TAInfoMutation) ResetEdge(name string) error {
	switch name {
	case tainfo.EdgeCtLog:
		m.ResetCtLog()
		return nil
	}
	return fmt.Errorf("unknown TAInfo edge %s", name)
}
