// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/ra_webs/ttp/ent/ctlogaudit"
	"github.com/akakou/ra_webs/ttp/ent/predicate"
	"github.com/akakou/ra_webs/ttp/ent/tacode"
	"github.com/akakou/ra_webs/ttp/ent/tainfo"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeCTLogAudit = "CTLogAudit"
	TypeTACode     = "TACode"
	TypeTAInfo     = "TAInfo"
)

// CTLogAuditMutation represents an operation that mutates the CTLogAudit nodes in the graph.
type CTLogAuditMutation struct {
	config
	op             Op
	typ            string
	id             *int
	is_valid       *bool
	latest_ct_id   *string
	clearedFields  map[string]struct{}
	ta_info        *int
	clearedta_info bool
	done           bool
	oldValue       func(context.Context) (*CTLogAudit, error)
	predicates     []predicate.CTLogAudit
}

var _ ent.Mutation = (*CTLogAuditMutation)(nil)

// ctlogauditOption allows management of the mutation configuration using functional options.
type ctlogauditOption func(*CTLogAuditMutation)

// newCTLogAuditMutation creates new mutation for the CTLogAudit entity.
func newCTLogAuditMutation(c config, op Op, opts ...ctlogauditOption) *CTLogAuditMutation {
	m := &CTLogAuditMutation{
		config:        c,
		op:            op,
		typ:           TypeCTLogAudit,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCTLogAuditID sets the ID field of the mutation.
func withCTLogAuditID(id int) ctlogauditOption {
	return func(m *CTLogAuditMutation) {
		var (
			err   error
			once  sync.Once
			value *CTLogAudit
		)
		m.oldValue = func(ctx context.Context) (*CTLogAudit, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().CTLogAudit.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCTLogAudit sets the old CTLogAudit of the mutation.
func withCTLogAudit(node *CTLogAudit) ctlogauditOption {
	return func(m *CTLogAuditMutation) {
		m.oldValue = func(context.Context) (*CTLogAudit, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CTLogAuditMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CTLogAuditMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CTLogAuditMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *CTLogAuditMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().CTLogAudit.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetIsValid sets the "is_valid" field.
func (m *CTLogAuditMutation) SetIsValid(b bool) {
	m.is_valid = &b
}

// IsValid returns the value of the "is_valid" field in the mutation.
func (m *CTLogAuditMutation) IsValid() (r bool, exists bool) {
	v := m.is_valid
	if v == nil {
		return
	}
	return *v, true
}

// OldIsValid returns the old "is_valid" field's value of the CTLogAudit entity.
// If the CTLogAudit object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CTLogAuditMutation) OldIsValid(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsValid is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsValid requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsValid: %w", err)
	}
	return oldValue.IsValid, nil
}

// ResetIsValid resets all changes to the "is_valid" field.
func (m *CTLogAuditMutation) ResetIsValid() {
	m.is_valid = nil
}

// SetLatestCtID sets the "latest_ct_id" field.
func (m *CTLogAuditMutation) SetLatestCtID(s string) {
	m.latest_ct_id = &s
}

// LatestCtID returns the value of the "latest_ct_id" field in the mutation.
func (m *CTLogAuditMutation) LatestCtID() (r string, exists bool) {
	v := m.latest_ct_id
	if v == nil {
		return
	}
	return *v, true
}

// OldLatestCtID returns the old "latest_ct_id" field's value of the CTLogAudit entity.
// If the CTLogAudit object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CTLogAuditMutation) OldLatestCtID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLatestCtID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLatestCtID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLatestCtID: %w", err)
	}
	return oldValue.LatestCtID, nil
}

// ResetLatestCtID resets all changes to the "latest_ct_id" field.
func (m *CTLogAuditMutation) ResetLatestCtID() {
	m.latest_ct_id = nil
}

// SetTaInfoID sets the "ta_info" edge to the TAInfo entity by id.
func (m *CTLogAuditMutation) SetTaInfoID(id int) {
	m.ta_info = &id
}

// ClearTaInfo clears the "ta_info" edge to the TAInfo entity.
func (m *CTLogAuditMutation) ClearTaInfo() {
	m.clearedta_info = true
}

// TaInfoCleared reports if the "ta_info" edge to the TAInfo entity was cleared.
func (m *CTLogAuditMutation) TaInfoCleared() bool {
	return m.clearedta_info
}

// TaInfoID returns the "ta_info" edge ID in the mutation.
func (m *CTLogAuditMutation) TaInfoID() (id int, exists bool) {
	if m.ta_info != nil {
		return *m.ta_info, true
	}
	return
}

// TaInfoIDs returns the "ta_info" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// TaInfoID instead. It exists only for internal usage by the builders.
func (m *CTLogAuditMutation) TaInfoIDs() (ids []int) {
	if id := m.ta_info; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetTaInfo resets all changes to the "ta_info" edge.
func (m *CTLogAuditMutation) ResetTaInfo() {
	m.ta_info = nil
	m.clearedta_info = false
}

// Where appends a list predicates to the CTLogAuditMutation builder.
func (m *CTLogAuditMutation) Where(ps ...predicate.CTLogAudit) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the CTLogAuditMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *CTLogAuditMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.CTLogAudit, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *CTLogAuditMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CTLogAuditMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (CTLogAudit).
func (m *CTLogAuditMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CTLogAuditMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.is_valid != nil {
		fields = append(fields, ctlogaudit.FieldIsValid)
	}
	if m.latest_ct_id != nil {
		fields = append(fields, ctlogaudit.FieldLatestCtID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CTLogAuditMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case ctlogaudit.FieldIsValid:
		return m.IsValid()
	case ctlogaudit.FieldLatestCtID:
		return m.LatestCtID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CTLogAuditMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case ctlogaudit.FieldIsValid:
		return m.OldIsValid(ctx)
	case ctlogaudit.FieldLatestCtID:
		return m.OldLatestCtID(ctx)
	}
	return nil, fmt.Errorf("unknown CTLogAudit field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CTLogAuditMutation) SetField(name string, value ent.Value) error {
	switch name {
	case ctlogaudit.FieldIsValid:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsValid(v)
		return nil
	case ctlogaudit.FieldLatestCtID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLatestCtID(v)
		return nil
	}
	return fmt.Errorf("unknown CTLogAudit field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CTLogAuditMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CTLogAuditMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CTLogAuditMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown CTLogAudit numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CTLogAuditMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CTLogAuditMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CTLogAuditMutation) ClearField(name string) error {
	return fmt.Errorf("unknown CTLogAudit nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CTLogAuditMutation) ResetField(name string) error {
	switch name {
	case ctlogaudit.FieldIsValid:
		m.ResetIsValid()
		return nil
	case ctlogaudit.FieldLatestCtID:
		m.ResetLatestCtID()
		return nil
	}
	return fmt.Errorf("unknown CTLogAudit field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CTLogAuditMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.ta_info != nil {
		edges = append(edges, ctlogaudit.EdgeTaInfo)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CTLogAuditMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case ctlogaudit.EdgeTaInfo:
		if id := m.ta_info; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CTLogAuditMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CTLogAuditMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CTLogAuditMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedta_info {
		edges = append(edges, ctlogaudit.EdgeTaInfo)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CTLogAuditMutation) EdgeCleared(name string) bool {
	switch name {
	case ctlogaudit.EdgeTaInfo:
		return m.clearedta_info
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CTLogAuditMutation) ClearEdge(name string) error {
	switch name {
	case ctlogaudit.EdgeTaInfo:
		m.ClearTaInfo()
		return nil
	}
	return fmt.Errorf("unknown CTLogAudit unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CTLogAuditMutation) ResetEdge(name string) error {
	switch name {
	case ctlogaudit.EdgeTaInfo:
		m.ResetTaInfo()
		return nil
	}
	return fmt.Errorf("unknown CTLogAudit edge %s", name)
}

// TACodeMutation represents an operation that mutates the TACode nodes in the graph.
type TACodeMutation struct {
	config
	op             Op
	typ            string
	id             *int
	product_id     *uint16
	addproduct_id  *int16
	commit_id      *string
	activated_at   *time.Time
	clearedFields  map[string]struct{}
	ta_info        map[int]struct{}
	removedta_info map[int]struct{}
	clearedta_info bool
	done           bool
	oldValue       func(context.Context) (*TACode, error)
	predicates     []predicate.TACode
}

var _ ent.Mutation = (*TACodeMutation)(nil)

// tacodeOption allows management of the mutation configuration using functional options.
type tacodeOption func(*TACodeMutation)

// newTACodeMutation creates new mutation for the TACode entity.
func newTACodeMutation(c config, op Op, opts ...tacodeOption) *TACodeMutation {
	m := &TACodeMutation{
		config:        c,
		op:            op,
		typ:           TypeTACode,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTACodeID sets the ID field of the mutation.
func withTACodeID(id int) tacodeOption {
	return func(m *TACodeMutation) {
		var (
			err   error
			once  sync.Once
			value *TACode
		)
		m.oldValue = func(ctx context.Context) (*TACode, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TACode.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTACode sets the old TACode of the mutation.
func withTACode(node *TACode) tacodeOption {
	return func(m *TACodeMutation) {
		m.oldValue = func(context.Context) (*TACode, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TACodeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TACodeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TACodeMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TACodeMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TACode.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetProductID sets the "product_id" field.
func (m *TACodeMutation) SetProductID(u uint16) {
	m.product_id = &u
	m.addproduct_id = nil
}

// ProductID returns the value of the "product_id" field in the mutation.
func (m *TACodeMutation) ProductID() (r uint16, exists bool) {
	v := m.product_id
	if v == nil {
		return
	}
	return *v, true
}

// OldProductID returns the old "product_id" field's value of the TACode entity.
// If the TACode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TACodeMutation) OldProductID(ctx context.Context) (v uint16, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProductID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProductID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProductID: %w", err)
	}
	return oldValue.ProductID, nil
}

// AddProductID adds u to the "product_id" field.
func (m *TACodeMutation) AddProductID(u int16) {
	if m.addproduct_id != nil {
		*m.addproduct_id += u
	} else {
		m.addproduct_id = &u
	}
}

// AddedProductID returns the value that was added to the "product_id" field in this mutation.
func (m *TACodeMutation) AddedProductID() (r int16, exists bool) {
	v := m.addproduct_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetProductID resets all changes to the "product_id" field.
func (m *TACodeMutation) ResetProductID() {
	m.product_id = nil
	m.addproduct_id = nil
}

// SetCommitID sets the "commit_id" field.
func (m *TACodeMutation) SetCommitID(s string) {
	m.commit_id = &s
}

// CommitID returns the value of the "commit_id" field in the mutation.
func (m *TACodeMutation) CommitID() (r string, exists bool) {
	v := m.commit_id
	if v == nil {
		return
	}
	return *v, true
}

// OldCommitID returns the old "commit_id" field's value of the TACode entity.
// If the TACode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TACodeMutation) OldCommitID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCommitID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCommitID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCommitID: %w", err)
	}
	return oldValue.CommitID, nil
}

// ResetCommitID resets all changes to the "commit_id" field.
func (m *TACodeMutation) ResetCommitID() {
	m.commit_id = nil
}

// SetActivatedAt sets the "activated_at" field.
func (m *TACodeMutation) SetActivatedAt(t time.Time) {
	m.activated_at = &t
}

// ActivatedAt returns the value of the "activated_at" field in the mutation.
func (m *TACodeMutation) ActivatedAt() (r time.Time, exists bool) {
	v := m.activated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldActivatedAt returns the old "activated_at" field's value of the TACode entity.
// If the TACode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TACodeMutation) OldActivatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldActivatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldActivatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldActivatedAt: %w", err)
	}
	return oldValue.ActivatedAt, nil
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (m *TACodeMutation) ClearActivatedAt() {
	m.activated_at = nil
	m.clearedFields[tacode.FieldActivatedAt] = struct{}{}
}

// ActivatedAtCleared returns if the "activated_at" field was cleared in this mutation.
func (m *TACodeMutation) ActivatedAtCleared() bool {
	_, ok := m.clearedFields[tacode.FieldActivatedAt]
	return ok
}

// ResetActivatedAt resets all changes to the "activated_at" field.
func (m *TACodeMutation) ResetActivatedAt() {
	m.activated_at = nil
	delete(m.clearedFields, tacode.FieldActivatedAt)
}

// AddTaInfoIDs adds the "ta_info" edge to the TAInfo entity by ids.
func (m *TACodeMutation) AddTaInfoIDs(ids ...int) {
	if m.ta_info == nil {
		m.ta_info = make(map[int]struct{})
	}
	for i := range ids {
		m.ta_info[ids[i]] = struct{}{}
	}
}

// ClearTaInfo clears the "ta_info" edge to the TAInfo entity.
func (m *TACodeMutation) ClearTaInfo() {
	m.clearedta_info = true
}

// TaInfoCleared reports if the "ta_info" edge to the TAInfo entity was cleared.
func (m *TACodeMutation) TaInfoCleared() bool {
	return m.clearedta_info
}

// RemoveTaInfoIDs removes the "ta_info" edge to the TAInfo entity by IDs.
func (m *TACodeMutation) RemoveTaInfoIDs(ids ...int) {
	if m.removedta_info == nil {
		m.removedta_info = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.ta_info, ids[i])
		m.removedta_info[ids[i]] = struct{}{}
	}
}

// RemovedTaInfo returns the removed IDs of the "ta_info" edge to the TAInfo entity.
func (m *TACodeMutation) RemovedTaInfoIDs() (ids []int) {
	for id := range m.removedta_info {
		ids = append(ids, id)
	}
	return
}

// TaInfoIDs returns the "ta_info" edge IDs in the mutation.
func (m *TACodeMutation) TaInfoIDs() (ids []int) {
	for id := range m.ta_info {
		ids = append(ids, id)
	}
	return
}

// ResetTaInfo resets all changes to the "ta_info" edge.
func (m *TACodeMutation) ResetTaInfo() {
	m.ta_info = nil
	m.clearedta_info = false
	m.removedta_info = nil
}

// Where appends a list predicates to the TACodeMutation builder.
func (m *TACodeMutation) Where(ps ...predicate.TACode) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TACodeMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TACodeMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TACode, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TACodeMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TACodeMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TACode).
func (m *TACodeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TACodeMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.product_id != nil {
		fields = append(fields, tacode.FieldProductID)
	}
	if m.commit_id != nil {
		fields = append(fields, tacode.FieldCommitID)
	}
	if m.activated_at != nil {
		fields = append(fields, tacode.FieldActivatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TACodeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case tacode.FieldProductID:
		return m.ProductID()
	case tacode.FieldCommitID:
		return m.CommitID()
	case tacode.FieldActivatedAt:
		return m.ActivatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TACodeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case tacode.FieldProductID:
		return m.OldProductID(ctx)
	case tacode.FieldCommitID:
		return m.OldCommitID(ctx)
	case tacode.FieldActivatedAt:
		return m.OldActivatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown TACode field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TACodeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case tacode.FieldProductID:
		v, ok := value.(uint16)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProductID(v)
		return nil
	case tacode.FieldCommitID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCommitID(v)
		return nil
	case tacode.FieldActivatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetActivatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown TACode field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TACodeMutation) AddedFields() []string {
	var fields []string
	if m.addproduct_id != nil {
		fields = append(fields, tacode.FieldProductID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TACodeMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case tacode.FieldProductID:
		return m.AddedProductID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TACodeMutation) AddField(name string, value ent.Value) error {
	switch name {
	case tacode.FieldProductID:
		v, ok := value.(int16)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddProductID(v)
		return nil
	}
	return fmt.Errorf("unknown TACode numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TACodeMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(tacode.FieldActivatedAt) {
		fields = append(fields, tacode.FieldActivatedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TACodeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TACodeMutation) ClearField(name string) error {
	switch name {
	case tacode.FieldActivatedAt:
		m.ClearActivatedAt()
		return nil
	}
	return fmt.Errorf("unknown TACode nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TACodeMutation) ResetField(name string) error {
	switch name {
	case tacode.FieldProductID:
		m.ResetProductID()
		return nil
	case tacode.FieldCommitID:
		m.ResetCommitID()
		return nil
	case tacode.FieldActivatedAt:
		m.ResetActivatedAt()
		return nil
	}
	return fmt.Errorf("unknown TACode field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TACodeMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.ta_info != nil {
		edges = append(edges, tacode.EdgeTaInfo)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TACodeMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case tacode.EdgeTaInfo:
		ids := make([]ent.Value, 0, len(m.ta_info))
		for id := range m.ta_info {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TACodeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedta_info != nil {
		edges = append(edges, tacode.EdgeTaInfo)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TACodeMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case tacode.EdgeTaInfo:
		ids := make([]ent.Value, 0, len(m.removedta_info))
		for id := range m.removedta_info {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TACodeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedta_info {
		edges = append(edges, tacode.EdgeTaInfo)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TACodeMutation) EdgeCleared(name string) bool {
	switch name {
	case tacode.EdgeTaInfo:
		return m.clearedta_info
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TACodeMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown TACode unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TACodeMutation) ResetEdge(name string) error {
	switch name {
	case tacode.EdgeTaInfo:
		m.ResetTaInfo()
		return nil
	}
	return fmt.Errorf("unknown TACode edge %s", name)
}

// TAInfoMutation represents an operation that mutates the TAInfo nodes in the graph.
type TAInfoMutation struct {
	config
	op             Op
	typ            string
	id             *int
	domain         *string
	git_repository *string
	clearedFields  map[string]struct{}
	ct_log         *int
	clearedct_log  bool
	ta_code        map[int]struct{}
	removedta_code map[int]struct{}
	clearedta_code bool
	done           bool
	oldValue       func(context.Context) (*TAInfo, error)
	predicates     []predicate.TAInfo
}

var _ ent.Mutation = (*TAInfoMutation)(nil)

// tainfoOption allows management of the mutation configuration using functional options.
type tainfoOption func(*TAInfoMutation)

// newTAInfoMutation creates new mutation for the TAInfo entity.
func newTAInfoMutation(c config, op Op, opts ...tainfoOption) *TAInfoMutation {
	m := &TAInfoMutation{
		config:        c,
		op:            op,
		typ:           TypeTAInfo,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTAInfoID sets the ID field of the mutation.
func withTAInfoID(id int) tainfoOption {
	return func(m *TAInfoMutation) {
		var (
			err   error
			once  sync.Once
			value *TAInfo
		)
		m.oldValue = func(ctx context.Context) (*TAInfo, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TAInfo.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTAInfo sets the old TAInfo of the mutation.
func withTAInfo(node *TAInfo) tainfoOption {
	return func(m *TAInfoMutation) {
		m.oldValue = func(context.Context) (*TAInfo, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TAInfoMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TAInfoMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TAInfoMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TAInfoMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TAInfo.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetDomain sets the "domain" field.
func (m *TAInfoMutation) SetDomain(s string) {
	m.domain = &s
}

// Domain returns the value of the "domain" field in the mutation.
func (m *TAInfoMutation) Domain() (r string, exists bool) {
	v := m.domain
	if v == nil {
		return
	}
	return *v, true
}

// OldDomain returns the old "domain" field's value of the TAInfo entity.
// If the TAInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TAInfoMutation) OldDomain(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDomain is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDomain requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDomain: %w", err)
	}
	return oldValue.Domain, nil
}

// ResetDomain resets all changes to the "domain" field.
func (m *TAInfoMutation) ResetDomain() {
	m.domain = nil
}

// SetGitRepository sets the "git_repository" field.
func (m *TAInfoMutation) SetGitRepository(s string) {
	m.git_repository = &s
}

// GitRepository returns the value of the "git_repository" field in the mutation.
func (m *TAInfoMutation) GitRepository() (r string, exists bool) {
	v := m.git_repository
	if v == nil {
		return
	}
	return *v, true
}

// OldGitRepository returns the old "git_repository" field's value of the TAInfo entity.
// If the TAInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TAInfoMutation) OldGitRepository(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGitRepository is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGitRepository requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGitRepository: %w", err)
	}
	return oldValue.GitRepository, nil
}

// ResetGitRepository resets all changes to the "git_repository" field.
func (m *TAInfoMutation) ResetGitRepository() {
	m.git_repository = nil
}

// SetCtLogID sets the "ct_log" edge to the CTLogAudit entity by id.
func (m *TAInfoMutation) SetCtLogID(id int) {
	m.ct_log = &id
}

// ClearCtLog clears the "ct_log" edge to the CTLogAudit entity.
func (m *TAInfoMutation) ClearCtLog() {
	m.clearedct_log = true
}

// CtLogCleared reports if the "ct_log" edge to the CTLogAudit entity was cleared.
func (m *TAInfoMutation) CtLogCleared() bool {
	return m.clearedct_log
}

// CtLogID returns the "ct_log" edge ID in the mutation.
func (m *TAInfoMutation) CtLogID() (id int, exists bool) {
	if m.ct_log != nil {
		return *m.ct_log, true
	}
	return
}

// CtLogIDs returns the "ct_log" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// CtLogID instead. It exists only for internal usage by the builders.
func (m *TAInfoMutation) CtLogIDs() (ids []int) {
	if id := m.ct_log; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetCtLog resets all changes to the "ct_log" edge.
func (m *TAInfoMutation) ResetCtLog() {
	m.ct_log = nil
	m.clearedct_log = false
}

// AddTaCodeIDs adds the "ta_code" edge to the TACode entity by ids.
func (m *TAInfoMutation) AddTaCodeIDs(ids ...int) {
	if m.ta_code == nil {
		m.ta_code = make(map[int]struct{})
	}
	for i := range ids {
		m.ta_code[ids[i]] = struct{}{}
	}
}

// ClearTaCode clears the "ta_code" edge to the TACode entity.
func (m *TAInfoMutation) ClearTaCode() {
	m.clearedta_code = true
}

// TaCodeCleared reports if the "ta_code" edge to the TACode entity was cleared.
func (m *TAInfoMutation) TaCodeCleared() bool {
	return m.clearedta_code
}

// RemoveTaCodeIDs removes the "ta_code" edge to the TACode entity by IDs.
func (m *TAInfoMutation) RemoveTaCodeIDs(ids ...int) {
	if m.removedta_code == nil {
		m.removedta_code = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.ta_code, ids[i])
		m.removedta_code[ids[i]] = struct{}{}
	}
}

// RemovedTaCode returns the removed IDs of the "ta_code" edge to the TACode entity.
func (m *TAInfoMutation) RemovedTaCodeIDs() (ids []int) {
	for id := range m.removedta_code {
		ids = append(ids, id)
	}
	return
}

// TaCodeIDs returns the "ta_code" edge IDs in the mutation.
func (m *TAInfoMutation) TaCodeIDs() (ids []int) {
	for id := range m.ta_code {
		ids = append(ids, id)
	}
	return
}

// ResetTaCode resets all changes to the "ta_code" edge.
func (m *TAInfoMutation) ResetTaCode() {
	m.ta_code = nil
	m.clearedta_code = false
	m.removedta_code = nil
}

// Where appends a list predicates to the TAInfoMutation builder.
func (m *TAInfoMutation) Where(ps ...predicate.TAInfo) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TAInfoMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TAInfoMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TAInfo, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TAInfoMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TAInfoMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TAInfo).
func (m *TAInfoMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TAInfoMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.domain != nil {
		fields = append(fields, tainfo.FieldDomain)
	}
	if m.git_repository != nil {
		fields = append(fields, tainfo.FieldGitRepository)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TAInfoMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case tainfo.FieldDomain:
		return m.Domain()
	case tainfo.FieldGitRepository:
		return m.GitRepository()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TAInfoMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case tainfo.FieldDomain:
		return m.OldDomain(ctx)
	case tainfo.FieldGitRepository:
		return m.OldGitRepository(ctx)
	}
	return nil, fmt.Errorf("unknown TAInfo field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TAInfoMutation) SetField(name string, value ent.Value) error {
	switch name {
	case tainfo.FieldDomain:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDomain(v)
		return nil
	case tainfo.FieldGitRepository:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGitRepository(v)
		return nil
	}
	return fmt.Errorf("unknown TAInfo field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TAInfoMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TAInfoMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TAInfoMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown TAInfo numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TAInfoMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TAInfoMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TAInfoMutation) ClearField(name string) error {
	return fmt.Errorf("unknown TAInfo nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TAInfoMutation) ResetField(name string) error {
	switch name {
	case tainfo.FieldDomain:
		m.ResetDomain()
		return nil
	case tainfo.FieldGitRepository:
		m.ResetGitRepository()
		return nil
	}
	return fmt.Errorf("unknown TAInfo field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TAInfoMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.ct_log != nil {
		edges = append(edges, tainfo.EdgeCtLog)
	}
	if m.ta_code != nil {
		edges = append(edges, tainfo.EdgeTaCode)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TAInfoMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case tainfo.EdgeCtLog:
		if id := m.ct_log; id != nil {
			return []ent.Value{*id}
		}
	case tainfo.EdgeTaCode:
		ids := make([]ent.Value, 0, len(m.ta_code))
		for id := range m.ta_code {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TAInfoMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedta_code != nil {
		edges = append(edges, tainfo.EdgeTaCode)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TAInfoMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case tainfo.EdgeTaCode:
		ids := make([]ent.Value, 0, len(m.removedta_code))
		for id := range m.removedta_code {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TAInfoMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedct_log {
		edges = append(edges, tainfo.EdgeCtLog)
	}
	if m.clearedta_code {
		edges = append(edges, tainfo.EdgeTaCode)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TAInfoMutation) EdgeCleared(name string) bool {
	switch name {
	case tainfo.EdgeCtLog:
		return m.clearedct_log
	case tainfo.EdgeTaCode:
		return m.clearedta_code
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TAInfoMutation) ClearEdge(name string) error {
	switch name {
	case tainfo.EdgeCtLog:
		m.ClearCtLog()
		return nil
	}
	return fmt.Errorf("unknown TAInfo unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TAInfoMutation) ResetEdge(name string) error {
	switch name {
	case tainfo.EdgeCtLog:
		m.ResetCtLog()
		return nil
	case tainfo.EdgeTaCode:
		m.ResetTaCode()
		return nil
	}
	return fmt.Errorf("unknown TAInfo edge %s", name)
}
