// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/ra_webs/ttp/ent/ta"
	"github.com/akakou/ra_webs/ttp/ent/taauditlog"
)

// TA is the model entity for the TA schema.
type TA struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Domain holds the value of the "domain" field.
	Domain string `json:"domain,omitempty"`
	// IP holds the value of the "ip" field.
	IP string `json:"ip,omitempty"`
	// Git holds the value of the "git" field.
	Git string `json:"git,omitempty"`
	// PublicKey holds the value of the "public_key" field.
	PublicKey string `json:"public_key,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TAQuery when eager-loading is set.
	Edges           TAEdges `json:"edges"`
	ta_audit_log_ta *int
	selectValues    sql.SelectValues
}

// TAEdges holds the relations/edges for other nodes in the graph.
type TAEdges struct {
	// AuditLog holds the value of the audit_log edge.
	AuditLog *TAAuditLog `json:"audit_log,omitempty"`
	// Code holds the value of the code edge.
	Code []*TACode `json:"code,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AuditLogOrErr returns the AuditLog value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TAEdges) AuditLogOrErr() (*TAAuditLog, error) {
	if e.loadedTypes[0] {
		if e.AuditLog == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: taauditlog.Label}
		}
		return e.AuditLog, nil
	}
	return nil, &NotLoadedError{edge: "audit_log"}
}

// CodeOrErr returns the Code value or an error if the edge
// was not loaded in eager-loading.
func (e TAEdges) CodeOrErr() ([]*TACode, error) {
	if e.loadedTypes[1] {
		return e.Code, nil
	}
	return nil, &NotLoadedError{edge: "code"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TA) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ta.FieldID:
			values[i] = new(sql.NullInt64)
		case ta.FieldDomain, ta.FieldIP, ta.FieldGit, ta.FieldPublicKey:
			values[i] = new(sql.NullString)
		case ta.ForeignKeys[0]: // ta_audit_log_ta
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TA fields.
func (t *TA) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ta.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case ta.FieldDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain", values[i])
			} else if value.Valid {
				t.Domain = value.String
			}
		case ta.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				t.IP = value.String
			}
		case ta.FieldGit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field git", values[i])
			} else if value.Valid {
				t.Git = value.String
			}
		case ta.FieldPublicKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_key", values[i])
			} else if value.Valid {
				t.PublicKey = value.String
			}
		case ta.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field ta_audit_log_ta", value)
			} else if value.Valid {
				t.ta_audit_log_ta = new(int)
				*t.ta_audit_log_ta = int(value.Int64)
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TA.
// This includes values selected through modifiers, order, etc.
func (t *TA) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// QueryAuditLog queries the "audit_log" edge of the TA entity.
func (t *TA) QueryAuditLog() *TAAuditLogQuery {
	return NewTAClient(t.config).QueryAuditLog(t)
}

// QueryCode queries the "code" edge of the TA entity.
func (t *TA) QueryCode() *TACodeQuery {
	return NewTAClient(t.config).QueryCode(t)
}

// Update returns a builder for updating this TA.
// Note that you need to call TA.Unwrap() before calling this method if this TA
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *TA) Update() *TAUpdateOne {
	return NewTAClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the TA entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *TA) Unwrap() *TA {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: TA is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *TA) String() string {
	var builder strings.Builder
	builder.WriteString("TA(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("domain=")
	builder.WriteString(t.Domain)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(t.IP)
	builder.WriteString(", ")
	builder.WriteString("git=")
	builder.WriteString(t.Git)
	builder.WriteString(", ")
	builder.WriteString("public_key=")
	builder.WriteString(t.PublicKey)
	builder.WriteByte(')')
	return builder.String()
}

// TAs is a parsable slice of TA.
type TAs []*TA
