// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/ra_webs/ttp/ent/ctlogaudit"
	"github.com/akakou/ra_webs/ttp/ent/tacode"
	"github.com/akakou/ra_webs/ttp/ent/tainfo"
)

// TAInfoCreate is the builder for creating a TAInfo entity.
type TAInfoCreate struct {
	config
	mutation *TAInfoMutation
	hooks    []Hook
}

// SetDomain sets the "domain" field.
func (tic *TAInfoCreate) SetDomain(s string) *TAInfoCreate {
	tic.mutation.SetDomain(s)
	return tic
}

// SetGitRepository sets the "git_repository" field.
func (tic *TAInfoCreate) SetGitRepository(s string) *TAInfoCreate {
	tic.mutation.SetGitRepository(s)
	return tic
}

// SetCtLogID sets the "ct_log" edge to the CTLogAudit entity by ID.
func (tic *TAInfoCreate) SetCtLogID(id int) *TAInfoCreate {
	tic.mutation.SetCtLogID(id)
	return tic
}

// SetNillableCtLogID sets the "ct_log" edge to the CTLogAudit entity by ID if the given value is not nil.
func (tic *TAInfoCreate) SetNillableCtLogID(id *int) *TAInfoCreate {
	if id != nil {
		tic = tic.SetCtLogID(*id)
	}
	return tic
}

// SetCtLog sets the "ct_log" edge to the CTLogAudit entity.
func (tic *TAInfoCreate) SetCtLog(c *CTLogAudit) *TAInfoCreate {
	return tic.SetCtLogID(c.ID)
}

// AddTaCodeIDs adds the "ta_code" edge to the TACode entity by IDs.
func (tic *TAInfoCreate) AddTaCodeIDs(ids ...int) *TAInfoCreate {
	tic.mutation.AddTaCodeIDs(ids...)
	return tic
}

// AddTaCode adds the "ta_code" edges to the TACode entity.
func (tic *TAInfoCreate) AddTaCode(t ...*TACode) *TAInfoCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tic.AddTaCodeIDs(ids...)
}

// Mutation returns the TAInfoMutation object of the builder.
func (tic *TAInfoCreate) Mutation() *TAInfoMutation {
	return tic.mutation
}

// Save creates the TAInfo in the database.
func (tic *TAInfoCreate) Save(ctx context.Context) (*TAInfo, error) {
	return withHooks(ctx, tic.sqlSave, tic.mutation, tic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tic *TAInfoCreate) SaveX(ctx context.Context) *TAInfo {
	v, err := tic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tic *TAInfoCreate) Exec(ctx context.Context) error {
	_, err := tic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tic *TAInfoCreate) ExecX(ctx context.Context) {
	if err := tic.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tic *TAInfoCreate) check() error {
	if _, ok := tic.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "TAInfo.domain"`)}
	}
	if _, ok := tic.mutation.GitRepository(); !ok {
		return &ValidationError{Name: "git_repository", err: errors.New(`ent: missing required field "TAInfo.git_repository"`)}
	}
	return nil
}

func (tic *TAInfoCreate) sqlSave(ctx context.Context) (*TAInfo, error) {
	if err := tic.check(); err != nil {
		return nil, err
	}
	_node, _spec := tic.createSpec()
	if err := sqlgraph.CreateNode(ctx, tic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tic.mutation.id = &_node.ID
	tic.mutation.done = true
	return _node, nil
}

func (tic *TAInfoCreate) createSpec() (*TAInfo, *sqlgraph.CreateSpec) {
	var (
		_node = &TAInfo{config: tic.config}
		_spec = sqlgraph.NewCreateSpec(tainfo.Table, sqlgraph.NewFieldSpec(tainfo.FieldID, field.TypeInt))
	)
	if value, ok := tic.mutation.Domain(); ok {
		_spec.SetField(tainfo.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := tic.mutation.GitRepository(); ok {
		_spec.SetField(tainfo.FieldGitRepository, field.TypeString, value)
		_node.GitRepository = value
	}
	if nodes := tic.mutation.CtLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tainfo.CtLogTable,
			Columns: []string{tainfo.CtLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ctlogaudit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ct_log_audit_ta_info = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tic.mutation.TaCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tainfo.TaCodeTable,
			Columns: tainfo.TaCodePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tacode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TAInfoCreateBulk is the builder for creating many TAInfo entities in bulk.
type TAInfoCreateBulk struct {
	config
	err      error
	builders []*TAInfoCreate
}

// Save creates the TAInfo entities in the database.
func (ticb *TAInfoCreateBulk) Save(ctx context.Context) ([]*TAInfo, error) {
	if ticb.err != nil {
		return nil, ticb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ticb.builders))
	nodes := make([]*TAInfo, len(ticb.builders))
	mutators := make([]Mutator, len(ticb.builders))
	for i := range ticb.builders {
		func(i int, root context.Context) {
			builder := ticb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TAInfoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ticb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ticb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ticb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ticb *TAInfoCreateBulk) SaveX(ctx context.Context) []*TAInfo {
	v, err := ticb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ticb *TAInfoCreateBulk) Exec(ctx context.Context) error {
	_, err := ticb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ticb *TAInfoCreateBulk) ExecX(ctx context.Context) {
	if err := ticb.Exec(ctx); err != nil {
		panic(err)
	}
}
