// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/ra_webs/ttp/ent/service"
	"github.com/akakou/ra_webs/ttp/ent/taserver"
)

// TAServer is the model entity for the TAServer schema.
type TAServer struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Domain holds the value of the "domain" field.
	Domain string `json:"domain,omitempty"`
	// HasActivated holds the value of the "has_activated" field.
	HasActivated bool `json:"has_activated,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TAServerQuery when eager-loading is set.
	Edges             TAServerEdges `json:"edges"`
	ta_server_service *int
	selectValues      sql.SelectValues
}

// TAServerEdges holds the relations/edges for other nodes in the graph.
type TAServerEdges struct {
	// Ta holds the value of the ta edge.
	Ta []*TA `json:"ta,omitempty"`
	// Service holds the value of the service edge.
	Service *Service `json:"service,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TaOrErr returns the Ta value or an error if the edge
// was not loaded in eager-loading.
func (e TAServerEdges) TaOrErr() ([]*TA, error) {
	if e.loadedTypes[0] {
		return e.Ta, nil
	}
	return nil, &NotLoadedError{edge: "ta"}
}

// ServiceOrErr returns the Service value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TAServerEdges) ServiceOrErr() (*Service, error) {
	if e.loadedTypes[1] {
		if e.Service == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: service.Label}
		}
		return e.Service, nil
	}
	return nil, &NotLoadedError{edge: "service"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TAServer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case taserver.FieldHasActivated:
			values[i] = new(sql.NullBool)
		case taserver.FieldID:
			values[i] = new(sql.NullInt64)
		case taserver.FieldDomain:
			values[i] = new(sql.NullString)
		case taserver.ForeignKeys[0]: // ta_server_service
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TAServer fields.
func (ts *TAServer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case taserver.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ts.ID = int(value.Int64)
		case taserver.FieldDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain", values[i])
			} else if value.Valid {
				ts.Domain = value.String
			}
		case taserver.FieldHasActivated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_activated", values[i])
			} else if value.Valid {
				ts.HasActivated = value.Bool
			}
		case taserver.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field ta_server_service", value)
			} else if value.Valid {
				ts.ta_server_service = new(int)
				*ts.ta_server_service = int(value.Int64)
			}
		default:
			ts.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TAServer.
// This includes values selected through modifiers, order, etc.
func (ts *TAServer) Value(name string) (ent.Value, error) {
	return ts.selectValues.Get(name)
}

// QueryTa queries the "ta" edge of the TAServer entity.
func (ts *TAServer) QueryTa() *TAQuery {
	return NewTAServerClient(ts.config).QueryTa(ts)
}

// QueryService queries the "service" edge of the TAServer entity.
func (ts *TAServer) QueryService() *ServiceQuery {
	return NewTAServerClient(ts.config).QueryService(ts)
}

// Update returns a builder for updating this TAServer.
// Note that you need to call TAServer.Unwrap() before calling this method if this TAServer
// was returned from a transaction, and the transaction was committed or rolled back.
func (ts *TAServer) Update() *TAServerUpdateOne {
	return NewTAServerClient(ts.config).UpdateOne(ts)
}

// Unwrap unwraps the TAServer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ts *TAServer) Unwrap() *TAServer {
	_tx, ok := ts.config.driver.(*txDriver)
	if !ok {
		panic("ent: TAServer is not a transactional entity")
	}
	ts.config.driver = _tx.drv
	return ts
}

// String implements the fmt.Stringer.
func (ts *TAServer) String() string {
	var builder strings.Builder
	builder.WriteString("TAServer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ts.ID))
	builder.WriteString("domain=")
	builder.WriteString(ts.Domain)
	builder.WriteString(", ")
	builder.WriteString("has_activated=")
	builder.WriteString(fmt.Sprintf("%v", ts.HasActivated))
	builder.WriteByte(')')
	return builder.String()
}

// TAServers is a parsable slice of TAServer.
type TAServers []*TAServer
