// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/ra_webs/ttp/ent/service"
	"github.com/akakou/ra_webs/ttp/ent/subscription"
	"github.com/akakou/ra_webs/ttp/ent/tacode"
	"github.com/akakou/ra_webs/ttp/ent/taserver"
	"github.com/akakou/ra_webs/ttp/ent/taviolation"
)

// TAServerCreate is the builder for creating a TAServer entity.
type TAServerCreate struct {
	config
	mutation *TAServerMutation
	hooks    []Hook
}

// SetDomain sets the "domain" field.
func (tsc *TAServerCreate) SetDomain(s string) *TAServerCreate {
	tsc.mutation.SetDomain(s)
	return tsc
}

// SetPublicKey sets the "public_key" field.
func (tsc *TAServerCreate) SetPublicKey(b []byte) *TAServerCreate {
	tsc.mutation.SetPublicKey(b)
	return tsc
}

// SetQuote sets the "quote" field.
func (tsc *TAServerCreate) SetQuote(s string) *TAServerCreate {
	tsc.mutation.SetQuote(s)
	return tsc
}

// SetHasActivated sets the "has_activated" field.
func (tsc *TAServerCreate) SetHasActivated(b bool) *TAServerCreate {
	tsc.mutation.SetHasActivated(b)
	return tsc
}

// AddViolationIDs adds the "violation" edge to the TAViolation entity by IDs.
func (tsc *TAServerCreate) AddViolationIDs(ids ...int) *TAServerCreate {
	tsc.mutation.AddViolationIDs(ids...)
	return tsc
}

// AddViolation adds the "violation" edges to the TAViolation entity.
func (tsc *TAServerCreate) AddViolation(t ...*TAViolation) *TAServerCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tsc.AddViolationIDs(ids...)
}

// SetCodeID sets the "code" edge to the TACode entity by ID.
func (tsc *TAServerCreate) SetCodeID(id int) *TAServerCreate {
	tsc.mutation.SetCodeID(id)
	return tsc
}

// SetNillableCodeID sets the "code" edge to the TACode entity by ID if the given value is not nil.
func (tsc *TAServerCreate) SetNillableCodeID(id *int) *TAServerCreate {
	if id != nil {
		tsc = tsc.SetCodeID(*id)
	}
	return tsc
}

// SetCode sets the "code" edge to the TACode entity.
func (tsc *TAServerCreate) SetCode(t *TACode) *TAServerCreate {
	return tsc.SetCodeID(t.ID)
}

// SetServiceID sets the "service" edge to the Service entity by ID.
func (tsc *TAServerCreate) SetServiceID(id int) *TAServerCreate {
	tsc.mutation.SetServiceID(id)
	return tsc
}

// SetNillableServiceID sets the "service" edge to the Service entity by ID if the given value is not nil.
func (tsc *TAServerCreate) SetNillableServiceID(id *int) *TAServerCreate {
	if id != nil {
		tsc = tsc.SetServiceID(*id)
	}
	return tsc
}

// SetService sets the "service" edge to the Service entity.
func (tsc *TAServerCreate) SetService(s *Service) *TAServerCreate {
	return tsc.SetServiceID(s.ID)
}

// AddSubscriptionIDs adds the "subscription" edge to the Subscription entity by IDs.
func (tsc *TAServerCreate) AddSubscriptionIDs(ids ...int) *TAServerCreate {
	tsc.mutation.AddSubscriptionIDs(ids...)
	return tsc
}

// AddSubscription adds the "subscription" edges to the Subscription entity.
func (tsc *TAServerCreate) AddSubscription(s ...*Subscription) *TAServerCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tsc.AddSubscriptionIDs(ids...)
}

// Mutation returns the TAServerMutation object of the builder.
func (tsc *TAServerCreate) Mutation() *TAServerMutation {
	return tsc.mutation
}

// Save creates the TAServer in the database.
func (tsc *TAServerCreate) Save(ctx context.Context) (*TAServer, error) {
	return withHooks(ctx, tsc.sqlSave, tsc.mutation, tsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tsc *TAServerCreate) SaveX(ctx context.Context) *TAServer {
	v, err := tsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tsc *TAServerCreate) Exec(ctx context.Context) error {
	_, err := tsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsc *TAServerCreate) ExecX(ctx context.Context) {
	if err := tsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tsc *TAServerCreate) check() error {
	if _, ok := tsc.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "TAServer.domain"`)}
	}
	if _, ok := tsc.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "public_key", err: errors.New(`ent: missing required field "TAServer.public_key"`)}
	}
	if _, ok := tsc.mutation.Quote(); !ok {
		return &ValidationError{Name: "quote", err: errors.New(`ent: missing required field "TAServer.quote"`)}
	}
	if _, ok := tsc.mutation.HasActivated(); !ok {
		return &ValidationError{Name: "has_activated", err: errors.New(`ent: missing required field "TAServer.has_activated"`)}
	}
	return nil
}

func (tsc *TAServerCreate) sqlSave(ctx context.Context) (*TAServer, error) {
	if err := tsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tsc.mutation.id = &_node.ID
	tsc.mutation.done = true
	return _node, nil
}

func (tsc *TAServerCreate) createSpec() (*TAServer, *sqlgraph.CreateSpec) {
	var (
		_node = &TAServer{config: tsc.config}
		_spec = sqlgraph.NewCreateSpec(taserver.Table, sqlgraph.NewFieldSpec(taserver.FieldID, field.TypeInt))
	)
	if value, ok := tsc.mutation.Domain(); ok {
		_spec.SetField(taserver.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := tsc.mutation.PublicKey(); ok {
		_spec.SetField(taserver.FieldPublicKey, field.TypeBytes, value)
		_node.PublicKey = value
	}
	if value, ok := tsc.mutation.Quote(); ok {
		_spec.SetField(taserver.FieldQuote, field.TypeString, value)
		_node.Quote = value
	}
	if value, ok := tsc.mutation.HasActivated(); ok {
		_spec.SetField(taserver.FieldHasActivated, field.TypeBool, value)
		_node.HasActivated = value
	}
	if nodes := tsc.mutation.ViolationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   taserver.ViolationTable,
			Columns: []string{taserver.ViolationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taviolation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tsc.mutation.CodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   taserver.CodeTable,
			Columns: []string{taserver.CodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tacode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ta_server_code = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tsc.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   taserver.ServiceTable,
			Columns: []string{taserver.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ta_server_service = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tsc.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   taserver.SubscriptionTable,
			Columns: []string{taserver.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TAServerCreateBulk is the builder for creating many TAServer entities in bulk.
type TAServerCreateBulk struct {
	config
	err      error
	builders []*TAServerCreate
}

// Save creates the TAServer entities in the database.
func (tscb *TAServerCreateBulk) Save(ctx context.Context) ([]*TAServer, error) {
	if tscb.err != nil {
		return nil, tscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tscb.builders))
	nodes := make([]*TAServer, len(tscb.builders))
	mutators := make([]Mutator, len(tscb.builders))
	for i := range tscb.builders {
		func(i int, root context.Context) {
			builder := tscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TAServerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tscb *TAServerCreateBulk) SaveX(ctx context.Context) []*TAServer {
	v, err := tscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tscb *TAServerCreateBulk) Exec(ctx context.Context) error {
	_, err := tscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tscb *TAServerCreateBulk) ExecX(ctx context.Context) {
	if err := tscb.Exec(ctx); err != nil {
		panic(err)
	}
}
