// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/ra_webs/ttp/ent/taserver"
	"github.com/akakou/ra_webs/ttp/ent/taviolation"
)

// TAViolationCreate is the builder for creating a TAViolation entity.
type TAViolationCreate struct {
	config
	mutation *TAViolationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (tvc *TAViolationCreate) SetCreatedAt(t time.Time) *TAViolationCreate {
	tvc.mutation.SetCreatedAt(t)
	return tvc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tvc *TAViolationCreate) SetNillableCreatedAt(t *time.Time) *TAViolationCreate {
	if t != nil {
		tvc.SetCreatedAt(*t)
	}
	return tvc
}

// SetServerID sets the "server" edge to the TAServer entity by ID.
func (tvc *TAViolationCreate) SetServerID(id int) *TAViolationCreate {
	tvc.mutation.SetServerID(id)
	return tvc
}

// SetNillableServerID sets the "server" edge to the TAServer entity by ID if the given value is not nil.
func (tvc *TAViolationCreate) SetNillableServerID(id *int) *TAViolationCreate {
	if id != nil {
		tvc = tvc.SetServerID(*id)
	}
	return tvc
}

// SetServer sets the "server" edge to the TAServer entity.
func (tvc *TAViolationCreate) SetServer(t *TAServer) *TAViolationCreate {
	return tvc.SetServerID(t.ID)
}

// Mutation returns the TAViolationMutation object of the builder.
func (tvc *TAViolationCreate) Mutation() *TAViolationMutation {
	return tvc.mutation
}

// Save creates the TAViolation in the database.
func (tvc *TAViolationCreate) Save(ctx context.Context) (*TAViolation, error) {
	tvc.defaults()
	return withHooks(ctx, tvc.sqlSave, tvc.mutation, tvc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tvc *TAViolationCreate) SaveX(ctx context.Context) *TAViolation {
	v, err := tvc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tvc *TAViolationCreate) Exec(ctx context.Context) error {
	_, err := tvc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tvc *TAViolationCreate) ExecX(ctx context.Context) {
	if err := tvc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tvc *TAViolationCreate) defaults() {
	if _, ok := tvc.mutation.CreatedAt(); !ok {
		v := taviolation.DefaultCreatedAt()
		tvc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tvc *TAViolationCreate) check() error {
	if _, ok := tvc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TAViolation.created_at"`)}
	}
	return nil
}

func (tvc *TAViolationCreate) sqlSave(ctx context.Context) (*TAViolation, error) {
	if err := tvc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tvc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tvc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tvc.mutation.id = &_node.ID
	tvc.mutation.done = true
	return _node, nil
}

func (tvc *TAViolationCreate) createSpec() (*TAViolation, *sqlgraph.CreateSpec) {
	var (
		_node = &TAViolation{config: tvc.config}
		_spec = sqlgraph.NewCreateSpec(taviolation.Table, sqlgraph.NewFieldSpec(taviolation.FieldID, field.TypeInt))
	)
	if value, ok := tvc.mutation.CreatedAt(); ok {
		_spec.SetField(taviolation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := tvc.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   taviolation.ServerTable,
			Columns: []string{taviolation.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taserver.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ta_violation_server = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TAViolationCreateBulk is the builder for creating many TAViolation entities in bulk.
type TAViolationCreateBulk struct {
	config
	err      error
	builders []*TAViolationCreate
}

// Save creates the TAViolation entities in the database.
func (tvcb *TAViolationCreateBulk) Save(ctx context.Context) ([]*TAViolation, error) {
	if tvcb.err != nil {
		return nil, tvcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tvcb.builders))
	nodes := make([]*TAViolation, len(tvcb.builders))
	mutators := make([]Mutator, len(tvcb.builders))
	for i := range tvcb.builders {
		func(i int, root context.Context) {
			builder := tvcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TAViolationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tvcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tvcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tvcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tvcb *TAViolationCreateBulk) SaveX(ctx context.Context) []*TAViolation {
	v, err := tvcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tvcb *TAViolationCreateBulk) Exec(ctx context.Context) error {
	_, err := tvcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tvcb *TAViolationCreateBulk) ExecX(ctx context.Context) {
	if err := tvcb.Exec(ctx); err != nil {
		panic(err)
	}
}
