// Code generated by ent, DO NOT EDIT.

package tainfo

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tainfo type in the database.
	Label = "ta_info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDomain holds the string denoting the domain field in the database.
	FieldDomain = "domain"
	// FieldPublicKey holds the string denoting the public_key field in the database.
	FieldPublicKey = "public_key"
	// FieldAttestation holds the string denoting the attestation field in the database.
	FieldAttestation = "attestation"
	// EdgeCtLog holds the string denoting the ct_log edge name in mutations.
	EdgeCtLog = "ct_log"
	// Table holds the table name of the tainfo in the database.
	Table = "ta_infos"
	// CtLogTable is the table that holds the ct_log relation/edge.
	CtLogTable = "ct_logs"
	// CtLogInverseTable is the table name for the CTLog entity.
	// It exists in this package in order to avoid circular dependency with the "ctlog" package.
	CtLogInverseTable = "ct_logs"
	// CtLogColumn is the table column denoting the ct_log relation/edge.
	CtLogColumn = "ct_log_ta_info"
)

// Columns holds all SQL columns for tainfo fields.
var Columns = []string{
	FieldID,
	FieldDomain,
	FieldPublicKey,
	FieldAttestation,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the TAInfo queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDomain orders the results by the domain field.
func ByDomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomain, opts...).ToFunc()
}

// ByAttestation orders the results by the attestation field.
func ByAttestation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttestation, opts...).ToFunc()
}

// ByCtLogCount orders the results by ct_log count.
func ByCtLogCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCtLogStep(), opts...)
	}
}

// ByCtLog orders the results by ct_log terms.
func ByCtLog(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCtLogStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCtLogStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CtLogInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, CtLogTable, CtLogColumn),
	)
}
