// Code generated by ent, DO NOT EDIT.

package tainfo

import (
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/ra_webs/ttp/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldLTE(FieldID, id))
}

// Domain applies equality check predicate on the "domain" field. It's identical to DomainEQ.
func Domain(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldEQ(FieldDomain, v))
}

// PublicKey applies equality check predicate on the "public_key" field. It's identical to PublicKeyEQ.
func PublicKey(v []byte) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldEQ(FieldPublicKey, v))
}

// Attestation applies equality check predicate on the "attestation" field. It's identical to AttestationEQ.
func Attestation(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldEQ(FieldAttestation, v))
}

// DomainEQ applies the EQ predicate on the "domain" field.
func DomainEQ(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldEQ(FieldDomain, v))
}

// DomainNEQ applies the NEQ predicate on the "domain" field.
func DomainNEQ(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldNEQ(FieldDomain, v))
}

// DomainIn applies the In predicate on the "domain" field.
func DomainIn(vs ...string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldIn(FieldDomain, vs...))
}

// DomainNotIn applies the NotIn predicate on the "domain" field.
func DomainNotIn(vs ...string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldNotIn(FieldDomain, vs...))
}

// DomainGT applies the GT predicate on the "domain" field.
func DomainGT(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldGT(FieldDomain, v))
}

// DomainGTE applies the GTE predicate on the "domain" field.
func DomainGTE(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldGTE(FieldDomain, v))
}

// DomainLT applies the LT predicate on the "domain" field.
func DomainLT(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldLT(FieldDomain, v))
}

// DomainLTE applies the LTE predicate on the "domain" field.
func DomainLTE(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldLTE(FieldDomain, v))
}

// DomainContains applies the Contains predicate on the "domain" field.
func DomainContains(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldContains(FieldDomain, v))
}

// DomainHasPrefix applies the HasPrefix predicate on the "domain" field.
func DomainHasPrefix(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldHasPrefix(FieldDomain, v))
}

// DomainHasSuffix applies the HasSuffix predicate on the "domain" field.
func DomainHasSuffix(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldHasSuffix(FieldDomain, v))
}

// DomainEqualFold applies the EqualFold predicate on the "domain" field.
func DomainEqualFold(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldEqualFold(FieldDomain, v))
}

// DomainContainsFold applies the ContainsFold predicate on the "domain" field.
func DomainContainsFold(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldContainsFold(FieldDomain, v))
}

// PublicKeyEQ applies the EQ predicate on the "public_key" field.
func PublicKeyEQ(v []byte) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldEQ(FieldPublicKey, v))
}

// PublicKeyNEQ applies the NEQ predicate on the "public_key" field.
func PublicKeyNEQ(v []byte) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldNEQ(FieldPublicKey, v))
}

// PublicKeyIn applies the In predicate on the "public_key" field.
func PublicKeyIn(vs ...[]byte) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldIn(FieldPublicKey, vs...))
}

// PublicKeyNotIn applies the NotIn predicate on the "public_key" field.
func PublicKeyNotIn(vs ...[]byte) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldNotIn(FieldPublicKey, vs...))
}

// PublicKeyGT applies the GT predicate on the "public_key" field.
func PublicKeyGT(v []byte) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldGT(FieldPublicKey, v))
}

// PublicKeyGTE applies the GTE predicate on the "public_key" field.
func PublicKeyGTE(v []byte) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldGTE(FieldPublicKey, v))
}

// PublicKeyLT applies the LT predicate on the "public_key" field.
func PublicKeyLT(v []byte) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldLT(FieldPublicKey, v))
}

// PublicKeyLTE applies the LTE predicate on the "public_key" field.
func PublicKeyLTE(v []byte) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldLTE(FieldPublicKey, v))
}

// AttestationEQ applies the EQ predicate on the "attestation" field.
func AttestationEQ(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldEQ(FieldAttestation, v))
}

// AttestationNEQ applies the NEQ predicate on the "attestation" field.
func AttestationNEQ(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldNEQ(FieldAttestation, v))
}

// AttestationIn applies the In predicate on the "attestation" field.
func AttestationIn(vs ...string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldIn(FieldAttestation, vs...))
}

// AttestationNotIn applies the NotIn predicate on the "attestation" field.
func AttestationNotIn(vs ...string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldNotIn(FieldAttestation, vs...))
}

// AttestationGT applies the GT predicate on the "attestation" field.
func AttestationGT(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldGT(FieldAttestation, v))
}

// AttestationGTE applies the GTE predicate on the "attestation" field.
func AttestationGTE(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldGTE(FieldAttestation, v))
}

// AttestationLT applies the LT predicate on the "attestation" field.
func AttestationLT(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldLT(FieldAttestation, v))
}

// AttestationLTE applies the LTE predicate on the "attestation" field.
func AttestationLTE(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldLTE(FieldAttestation, v))
}

// AttestationContains applies the Contains predicate on the "attestation" field.
func AttestationContains(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldContains(FieldAttestation, v))
}

// AttestationHasPrefix applies the HasPrefix predicate on the "attestation" field.
func AttestationHasPrefix(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldHasPrefix(FieldAttestation, v))
}

// AttestationHasSuffix applies the HasSuffix predicate on the "attestation" field.
func AttestationHasSuffix(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldHasSuffix(FieldAttestation, v))
}

// AttestationEqualFold applies the EqualFold predicate on the "attestation" field.
func AttestationEqualFold(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldEqualFold(FieldAttestation, v))
}

// AttestationContainsFold applies the ContainsFold predicate on the "attestation" field.
func AttestationContainsFold(v string) predicate.TAInfo {
	return predicate.TAInfo(sql.FieldContainsFold(FieldAttestation, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TAInfo) predicate.TAInfo {
	return predicate.TAInfo(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TAInfo) predicate.TAInfo {
	return predicate.TAInfo(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TAInfo) predicate.TAInfo {
	return predicate.TAInfo(sql.NotPredicates(p))
}
