version: '3'
services:
  ta_example:
    tty: true
    build: ./docker
    network_mode: host
    volumes:
      - ./ta:/ta
      - ./core:/core
      - ./test:/test
      - /dev:/dev
    working_dir: /ta/example
    command: bash -c 'mount -o remount,exec /dev && ego-go build -buildvcs=false -trimpath=true && ego sign example && source /test/issue_service.sh && ego run example'
    privileged: true
    environment:
      - OE_SIMULATION=0
    env_file:
      - test/env/ta.env
      - test/env/common.env
    profiles:
      - ta

  monitor:
    build: ./docker
    volumes:
      - ./monitor:/monitor
      - ./core:/core
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /monitor/serv
    command: bash -c 'go mod tidy && go run main.go'
    env_file:
      - test/env/monitor.env
      - test/env/common.env
    privileged: true
    tty: true
    profiles:
      - monitor

  tunnel:
    restart: unless-stopped
    image: cloudflare/cloudflared
    command: tunnel --url http://monitor:8080 
    profiles:
      - monitor
