version: '3'
services:
  ta_example:
    tty: true
    build: ./docker
    ports:
      - "8443:8443"
    volumes:
      - ./ta:/ta
      - ./core:/core
      - /dev:/dev
    restart: unless-stopped
    working_dir: /ta/example
    command: bash -c 'go mod tidy && go run main.go'
    network_mode: host

  ttp:
    build: ./docker
    ports:
      - "8000:8000"
    volumes:
      - ./ttp:/ttp
      - ./core:/core
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /ttp/serv
    command: bash -c 'go mod tidy && go run main.go'
    network_mode: host
    env_file:
      - test/env/ttp.env
    privileged: true
    tty: true

  do:
    image: golang:latest
    ports:
      - "53:53/udp"
    volumes:
      - ./opt/domain-owner:/serv/domain-owner # Avoid to use /opt
      - ./core:/core
    working_dir: /serv/domain-owner/example
    command: bash -c 'go mod tidy && go run main.go'
    environment:
      - ZONE=test.ochano.co
      - SELF_IP=127.0.0.1
      - CA_NAME=letsencrypt.org
    network_mode: host
