// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ATLog is the predicate function for atlog builders.
type ATLog func(*sql.Selector)

// CTLog is the predicate function for ctlog builders.
type CTLog func(*sql.Selector)

// Subscription is the predicate function for subscription builders.
type Subscription func(*sql.Selector)

// TAViolation is the predicate function for taviolation builders.
type TAViolation func(*sql.Selector)
