// Code generated by ent, DO NOT EDIT.

package ta

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/akakou/ra_webs/ttp/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TA {
	return predicate.TA(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TA {
	return predicate.TA(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TA {
	return predicate.TA(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TA {
	return predicate.TA(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TA {
	return predicate.TA(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TA {
	return predicate.TA(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TA {
	return predicate.TA(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TA {
	return predicate.TA(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TA {
	return predicate.TA(sql.FieldLTE(FieldID, id))
}

// Domain applies equality check predicate on the "domain" field. It's identical to DomainEQ.
func Domain(v string) predicate.TA {
	return predicate.TA(sql.FieldEQ(FieldDomain, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.TA {
	return predicate.TA(sql.FieldEQ(FieldIP, v))
}

// Git applies equality check predicate on the "git" field. It's identical to GitEQ.
func Git(v string) predicate.TA {
	return predicate.TA(sql.FieldEQ(FieldGit, v))
}

// PublicKey applies equality check predicate on the "public_key" field. It's identical to PublicKeyEQ.
func PublicKey(v string) predicate.TA {
	return predicate.TA(sql.FieldEQ(FieldPublicKey, v))
}

// DomainEQ applies the EQ predicate on the "domain" field.
func DomainEQ(v string) predicate.TA {
	return predicate.TA(sql.FieldEQ(FieldDomain, v))
}

// DomainNEQ applies the NEQ predicate on the "domain" field.
func DomainNEQ(v string) predicate.TA {
	return predicate.TA(sql.FieldNEQ(FieldDomain, v))
}

// DomainIn applies the In predicate on the "domain" field.
func DomainIn(vs ...string) predicate.TA {
	return predicate.TA(sql.FieldIn(FieldDomain, vs...))
}

// DomainNotIn applies the NotIn predicate on the "domain" field.
func DomainNotIn(vs ...string) predicate.TA {
	return predicate.TA(sql.FieldNotIn(FieldDomain, vs...))
}

// DomainGT applies the GT predicate on the "domain" field.
func DomainGT(v string) predicate.TA {
	return predicate.TA(sql.FieldGT(FieldDomain, v))
}

// DomainGTE applies the GTE predicate on the "domain" field.
func DomainGTE(v string) predicate.TA {
	return predicate.TA(sql.FieldGTE(FieldDomain, v))
}

// DomainLT applies the LT predicate on the "domain" field.
func DomainLT(v string) predicate.TA {
	return predicate.TA(sql.FieldLT(FieldDomain, v))
}

// DomainLTE applies the LTE predicate on the "domain" field.
func DomainLTE(v string) predicate.TA {
	return predicate.TA(sql.FieldLTE(FieldDomain, v))
}

// DomainContains applies the Contains predicate on the "domain" field.
func DomainContains(v string) predicate.TA {
	return predicate.TA(sql.FieldContains(FieldDomain, v))
}

// DomainHasPrefix applies the HasPrefix predicate on the "domain" field.
func DomainHasPrefix(v string) predicate.TA {
	return predicate.TA(sql.FieldHasPrefix(FieldDomain, v))
}

// DomainHasSuffix applies the HasSuffix predicate on the "domain" field.
func DomainHasSuffix(v string) predicate.TA {
	return predicate.TA(sql.FieldHasSuffix(FieldDomain, v))
}

// DomainEqualFold applies the EqualFold predicate on the "domain" field.
func DomainEqualFold(v string) predicate.TA {
	return predicate.TA(sql.FieldEqualFold(FieldDomain, v))
}

// DomainContainsFold applies the ContainsFold predicate on the "domain" field.
func DomainContainsFold(v string) predicate.TA {
	return predicate.TA(sql.FieldContainsFold(FieldDomain, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.TA {
	return predicate.TA(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.TA {
	return predicate.TA(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.TA {
	return predicate.TA(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.TA {
	return predicate.TA(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.TA {
	return predicate.TA(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.TA {
	return predicate.TA(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.TA {
	return predicate.TA(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.TA {
	return predicate.TA(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.TA {
	return predicate.TA(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.TA {
	return predicate.TA(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.TA {
	return predicate.TA(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.TA {
	return predicate.TA(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.TA {
	return predicate.TA(sql.FieldContainsFold(FieldIP, v))
}

// GitEQ applies the EQ predicate on the "git" field.
func GitEQ(v string) predicate.TA {
	return predicate.TA(sql.FieldEQ(FieldGit, v))
}

// GitNEQ applies the NEQ predicate on the "git" field.
func GitNEQ(v string) predicate.TA {
	return predicate.TA(sql.FieldNEQ(FieldGit, v))
}

// GitIn applies the In predicate on the "git" field.
func GitIn(vs ...string) predicate.TA {
	return predicate.TA(sql.FieldIn(FieldGit, vs...))
}

// GitNotIn applies the NotIn predicate on the "git" field.
func GitNotIn(vs ...string) predicate.TA {
	return predicate.TA(sql.FieldNotIn(FieldGit, vs...))
}

// GitGT applies the GT predicate on the "git" field.
func GitGT(v string) predicate.TA {
	return predicate.TA(sql.FieldGT(FieldGit, v))
}

// GitGTE applies the GTE predicate on the "git" field.
func GitGTE(v string) predicate.TA {
	return predicate.TA(sql.FieldGTE(FieldGit, v))
}

// GitLT applies the LT predicate on the "git" field.
func GitLT(v string) predicate.TA {
	return predicate.TA(sql.FieldLT(FieldGit, v))
}

// GitLTE applies the LTE predicate on the "git" field.
func GitLTE(v string) predicate.TA {
	return predicate.TA(sql.FieldLTE(FieldGit, v))
}

// GitContains applies the Contains predicate on the "git" field.
func GitContains(v string) predicate.TA {
	return predicate.TA(sql.FieldContains(FieldGit, v))
}

// GitHasPrefix applies the HasPrefix predicate on the "git" field.
func GitHasPrefix(v string) predicate.TA {
	return predicate.TA(sql.FieldHasPrefix(FieldGit, v))
}

// GitHasSuffix applies the HasSuffix predicate on the "git" field.
func GitHasSuffix(v string) predicate.TA {
	return predicate.TA(sql.FieldHasSuffix(FieldGit, v))
}

// GitEqualFold applies the EqualFold predicate on the "git" field.
func GitEqualFold(v string) predicate.TA {
	return predicate.TA(sql.FieldEqualFold(FieldGit, v))
}

// GitContainsFold applies the ContainsFold predicate on the "git" field.
func GitContainsFold(v string) predicate.TA {
	return predicate.TA(sql.FieldContainsFold(FieldGit, v))
}

// PublicKeyEQ applies the EQ predicate on the "public_key" field.
func PublicKeyEQ(v string) predicate.TA {
	return predicate.TA(sql.FieldEQ(FieldPublicKey, v))
}

// PublicKeyNEQ applies the NEQ predicate on the "public_key" field.
func PublicKeyNEQ(v string) predicate.TA {
	return predicate.TA(sql.FieldNEQ(FieldPublicKey, v))
}

// PublicKeyIn applies the In predicate on the "public_key" field.
func PublicKeyIn(vs ...string) predicate.TA {
	return predicate.TA(sql.FieldIn(FieldPublicKey, vs...))
}

// PublicKeyNotIn applies the NotIn predicate on the "public_key" field.
func PublicKeyNotIn(vs ...string) predicate.TA {
	return predicate.TA(sql.FieldNotIn(FieldPublicKey, vs...))
}

// PublicKeyGT applies the GT predicate on the "public_key" field.
func PublicKeyGT(v string) predicate.TA {
	return predicate.TA(sql.FieldGT(FieldPublicKey, v))
}

// PublicKeyGTE applies the GTE predicate on the "public_key" field.
func PublicKeyGTE(v string) predicate.TA {
	return predicate.TA(sql.FieldGTE(FieldPublicKey, v))
}

// PublicKeyLT applies the LT predicate on the "public_key" field.
func PublicKeyLT(v string) predicate.TA {
	return predicate.TA(sql.FieldLT(FieldPublicKey, v))
}

// PublicKeyLTE applies the LTE predicate on the "public_key" field.
func PublicKeyLTE(v string) predicate.TA {
	return predicate.TA(sql.FieldLTE(FieldPublicKey, v))
}

// PublicKeyContains applies the Contains predicate on the "public_key" field.
func PublicKeyContains(v string) predicate.TA {
	return predicate.TA(sql.FieldContains(FieldPublicKey, v))
}

// PublicKeyHasPrefix applies the HasPrefix predicate on the "public_key" field.
func PublicKeyHasPrefix(v string) predicate.TA {
	return predicate.TA(sql.FieldHasPrefix(FieldPublicKey, v))
}

// PublicKeyHasSuffix applies the HasSuffix predicate on the "public_key" field.
func PublicKeyHasSuffix(v string) predicate.TA {
	return predicate.TA(sql.FieldHasSuffix(FieldPublicKey, v))
}

// PublicKeyEqualFold applies the EqualFold predicate on the "public_key" field.
func PublicKeyEqualFold(v string) predicate.TA {
	return predicate.TA(sql.FieldEqualFold(FieldPublicKey, v))
}

// PublicKeyContainsFold applies the ContainsFold predicate on the "public_key" field.
func PublicKeyContainsFold(v string) predicate.TA {
	return predicate.TA(sql.FieldContainsFold(FieldPublicKey, v))
}

// HasAuditLog applies the HasEdge predicate on the "audit_log" edge.
func HasAuditLog() predicate.TA {
	return predicate.TA(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, AuditLogTable, AuditLogColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuditLogWith applies the HasEdge predicate on the "audit_log" edge with a given conditions (other predicates).
func HasAuditLogWith(preds ...predicate.TAAuditLog) predicate.TA {
	return predicate.TA(func(s *sql.Selector) {
		step := newAuditLogStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCode applies the HasEdge predicate on the "code" edge.
func HasCode() predicate.TA {
	return predicate.TA(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, CodeTable, CodePrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCodeWith applies the HasEdge predicate on the "code" edge with a given conditions (other predicates).
func HasCodeWith(preds ...predicate.TACode) predicate.TA {
	return predicate.TA(func(s *sql.Selector) {
		step := newCodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TA) predicate.TA {
	return predicate.TA(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TA) predicate.TA {
	return predicate.TA(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TA) predicate.TA {
	return predicate.TA(sql.NotPredicates(p))
}
