// Code generated by ent, DO NOT EDIT.

package taserver

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the taserver type in the database.
	Label = "ta_server"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDomain holds the string denoting the domain field in the database.
	FieldDomain = "domain"
	// FieldHasActivated holds the string denoting the has_activated field in the database.
	FieldHasActivated = "has_activated"
	// EdgeTa holds the string denoting the ta edge name in mutations.
	EdgeTa = "ta"
	// EdgeService holds the string denoting the service edge name in mutations.
	EdgeService = "service"
	// Table holds the table name of the taserver in the database.
	Table = "ta_servers"
	// TaTable is the table that holds the ta relation/edge.
	TaTable = "tas"
	// TaInverseTable is the table name for the TA entity.
	// It exists in this package in order to avoid circular dependency with the "ta" package.
	TaInverseTable = "tas"
	// TaColumn is the table column denoting the ta relation/edge.
	TaColumn = "ta_server"
	// ServiceTable is the table that holds the service relation/edge.
	ServiceTable = "ta_servers"
	// ServiceInverseTable is the table name for the Service entity.
	// It exists in this package in order to avoid circular dependency with the "service" package.
	ServiceInverseTable = "services"
	// ServiceColumn is the table column denoting the service relation/edge.
	ServiceColumn = "ta_server_service"
)

// Columns holds all SQL columns for taserver fields.
var Columns = []string{
	FieldID,
	FieldDomain,
	FieldHasActivated,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "ta_servers"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"ta_server_service",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultHasActivated holds the default value on creation for the "has_activated" field.
	DefaultHasActivated bool
)

// OrderOption defines the ordering options for the TAServer queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDomain orders the results by the domain field.
func ByDomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomain, opts...).ToFunc()
}

// ByHasActivated orders the results by the has_activated field.
func ByHasActivated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasActivated, opts...).ToFunc()
}

// ByTaCount orders the results by ta count.
func ByTaCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTaStep(), opts...)
	}
}

// ByTa orders the results by ta terms.
func ByTa(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByServiceField orders the results by service field.
func ByServiceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServiceStep(), sql.OrderByField(field, opts...))
	}
}
func newTaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TaTable, TaColumn),
	)
}
func newServiceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ServiceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ServiceTable, ServiceColumn),
	)
}
