// Code generated by ent, DO NOT EDIT.

package taauditlog

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the taauditlog type in the database.
	Label = "ta_audit_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIsValid holds the string denoting the is_valid field in the database.
	FieldIsValid = "is_valid"
	// FieldLatestCtID holds the string denoting the latest_ct_id field in the database.
	FieldLatestCtID = "latest_ct_id"
	// EdgeTa holds the string denoting the ta edge name in mutations.
	EdgeTa = "ta"
	// Table holds the table name of the taauditlog in the database.
	Table = "ta_audit_logs"
	// TaTable is the table that holds the ta relation/edge.
	TaTable = "tas"
	// TaInverseTable is the table name for the TA entity.
	// It exists in this package in order to avoid circular dependency with the "ta" package.
	TaInverseTable = "tas"
	// TaColumn is the table column denoting the ta relation/edge.
	TaColumn = "ta_audit_log_ta"
)

// Columns holds all SQL columns for taauditlog fields.
var Columns = []string{
	FieldID,
	FieldIsValid,
	FieldLatestCtID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the TAAuditLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIsValid orders the results by the is_valid field.
func ByIsValid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsValid, opts...).ToFunc()
}

// ByLatestCtID orders the results by the latest_ct_id field.
func ByLatestCtID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatestCtID, opts...).ToFunc()
}

// ByTaField orders the results by ta field.
func ByTaField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaStep(), sql.OrderByField(field, opts...))
	}
}
func newTaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, TaTable, TaColumn),
	)
}
