// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/akakou/ra-webs/monitor/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/akakou/ra-webs/monitor/ent/atlog"
	"github.com/akakou/ra-webs/monitor/ent/ctlog"
	"github.com/akakou/ra-webs/monitor/ent/subscription"
	"github.com/akakou/ra-webs/monitor/ent/ta"
	"github.com/akakou/ra-webs/monitor/ent/violation"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ATLog is the client for interacting with the ATLog builders.
	ATLog *ATLogClient
	// CTLog is the client for interacting with the CTLog builders.
	CTLog *CTLogClient
	// Subscription is the client for interacting with the Subscription builders.
	Subscription *SubscriptionClient
	// TA is the client for interacting with the TA builders.
	TA *TAClient
	// Violation is the client for interacting with the Violation builders.
	Violation *ViolationClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ATLog = NewATLogClient(c.config)
	c.CTLog = NewCTLogClient(c.config)
	c.Subscription = NewSubscriptionClient(c.config)
	c.TA = NewTAClient(c.config)
	c.Violation = NewViolationClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		ATLog:        NewATLogClient(cfg),
		CTLog:        NewCTLogClient(cfg),
		Subscription: NewSubscriptionClient(cfg),
		TA:           NewTAClient(cfg),
		Violation:    NewViolationClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		ATLog:        NewATLogClient(cfg),
		CTLog:        NewCTLogClient(cfg),
		Subscription: NewSubscriptionClient(cfg),
		TA:           NewTAClient(cfg),
		Violation:    NewViolationClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ATLog.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.ATLog.Use(hooks...)
	c.CTLog.Use(hooks...)
	c.Subscription.Use(hooks...)
	c.TA.Use(hooks...)
	c.Violation.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.ATLog.Intercept(interceptors...)
	c.CTLog.Intercept(interceptors...)
	c.Subscription.Intercept(interceptors...)
	c.TA.Intercept(interceptors...)
	c.Violation.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ATLogMutation:
		return c.ATLog.mutate(ctx, m)
	case *CTLogMutation:
		return c.CTLog.mutate(ctx, m)
	case *SubscriptionMutation:
		return c.Subscription.mutate(ctx, m)
	case *TAMutation:
		return c.TA.mutate(ctx, m)
	case *ViolationMutation:
		return c.Violation.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ATLogClient is a client for the ATLog schema.
type ATLogClient struct {
	config
}

// NewATLogClient returns a client for the ATLog from the given config.
func NewATLogClient(c config) *ATLogClient {
	return &ATLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `atlog.Hooks(f(g(h())))`.
func (c *ATLogClient) Use(hooks ...Hook) {
	c.hooks.ATLog = append(c.hooks.ATLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `atlog.Intercept(f(g(h())))`.
func (c *ATLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.ATLog = append(c.inters.ATLog, interceptors...)
}

// Create returns a builder for creating a ATLog entity.
func (c *ATLogClient) Create() *ATLogCreate {
	mutation := newATLogMutation(c.config, OpCreate)
	return &ATLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ATLog entities.
func (c *ATLogClient) CreateBulk(builders ...*ATLogCreate) *ATLogCreateBulk {
	return &ATLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ATLogClient) MapCreateBulk(slice any, setFunc func(*ATLogCreate, int)) *ATLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ATLogCreateBulk{err: fmt.Errorf("calling to ATLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ATLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ATLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ATLog.
func (c *ATLogClient) Update() *ATLogUpdate {
	mutation := newATLogMutation(c.config, OpUpdate)
	return &ATLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ATLogClient) UpdateOne(al *ATLog) *ATLogUpdateOne {
	mutation := newATLogMutation(c.config, OpUpdateOne, withATLog(al))
	return &ATLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ATLogClient) UpdateOneID(id int) *ATLogUpdateOne {
	mutation := newATLogMutation(c.config, OpUpdateOne, withATLogID(id))
	return &ATLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ATLog.
func (c *ATLogClient) Delete() *ATLogDelete {
	mutation := newATLogMutation(c.config, OpDelete)
	return &ATLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ATLogClient) DeleteOne(al *ATLog) *ATLogDeleteOne {
	return c.DeleteOneID(al.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ATLogClient) DeleteOneID(id int) *ATLogDeleteOne {
	builder := c.Delete().Where(atlog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ATLogDeleteOne{builder}
}

// Query returns a query builder for ATLog.
func (c *ATLogClient) Query() *ATLogQuery {
	return &ATLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeATLog},
		inters: c.Interceptors(),
	}
}

// Get returns a ATLog entity by its id.
func (c *ATLogClient) Get(ctx context.Context, id int) (*ATLog, error) {
	return c.Query().Where(atlog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ATLogClient) GetX(ctx context.Context, id int) *ATLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTa queries the ta edge of a ATLog.
func (c *ATLogClient) QueryTa(al *ATLog) *TAQuery {
	query := (&TAClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := al.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(atlog.Table, atlog.FieldID, id),
			sqlgraph.To(ta.Table, ta.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, atlog.TaTable, atlog.TaColumn),
		)
		fromV = sqlgraph.Neighbors(al.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ATLogClient) Hooks() []Hook {
	return c.hooks.ATLog
}

// Interceptors returns the client interceptors.
func (c *ATLogClient) Interceptors() []Interceptor {
	return c.inters.ATLog
}

func (c *ATLogClient) mutate(ctx context.Context, m *ATLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ATLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ATLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ATLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ATLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ATLog mutation op: %q", m.Op())
	}
}

// CTLogClient is a client for the CTLog schema.
type CTLogClient struct {
	config
}

// NewCTLogClient returns a client for the CTLog from the given config.
func NewCTLogClient(c config) *CTLogClient {
	return &CTLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ctlog.Hooks(f(g(h())))`.
func (c *CTLogClient) Use(hooks ...Hook) {
	c.hooks.CTLog = append(c.hooks.CTLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ctlog.Intercept(f(g(h())))`.
func (c *CTLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.CTLog = append(c.inters.CTLog, interceptors...)
}

// Create returns a builder for creating a CTLog entity.
func (c *CTLogClient) Create() *CTLogCreate {
	mutation := newCTLogMutation(c.config, OpCreate)
	return &CTLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CTLog entities.
func (c *CTLogClient) CreateBulk(builders ...*CTLogCreate) *CTLogCreateBulk {
	return &CTLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CTLogClient) MapCreateBulk(slice any, setFunc func(*CTLogCreate, int)) *CTLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CTLogCreateBulk{err: fmt.Errorf("calling to CTLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CTLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CTLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CTLog.
func (c *CTLogClient) Update() *CTLogUpdate {
	mutation := newCTLogMutation(c.config, OpUpdate)
	return &CTLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CTLogClient) UpdateOne(cl *CTLog) *CTLogUpdateOne {
	mutation := newCTLogMutation(c.config, OpUpdateOne, withCTLog(cl))
	return &CTLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CTLogClient) UpdateOneID(id int) *CTLogUpdateOne {
	mutation := newCTLogMutation(c.config, OpUpdateOne, withCTLogID(id))
	return &CTLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CTLog.
func (c *CTLogClient) Delete() *CTLogDelete {
	mutation := newCTLogMutation(c.config, OpDelete)
	return &CTLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CTLogClient) DeleteOne(cl *CTLog) *CTLogDeleteOne {
	return c.DeleteOneID(cl.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CTLogClient) DeleteOneID(id int) *CTLogDeleteOne {
	builder := c.Delete().Where(ctlog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CTLogDeleteOne{builder}
}

// Query returns a query builder for CTLog.
func (c *CTLogClient) Query() *CTLogQuery {
	return &CTLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCTLog},
		inters: c.Interceptors(),
	}
}

// Get returns a CTLog entity by its id.
func (c *CTLogClient) Get(ctx context.Context, id int) (*CTLog, error) {
	return c.Query().Where(ctlog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CTLogClient) GetX(ctx context.Context, id int) *CTLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTa queries the ta edge of a CTLog.
func (c *CTLogClient) QueryTa(cl *CTLog) *TAQuery {
	query := (&TAClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := cl.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ctlog.Table, ctlog.FieldID, id),
			sqlgraph.To(ta.Table, ta.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ctlog.TaTable, ctlog.TaColumn),
		)
		fromV = sqlgraph.Neighbors(cl.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CTLogClient) Hooks() []Hook {
	return c.hooks.CTLog
}

// Interceptors returns the client interceptors.
func (c *CTLogClient) Interceptors() []Interceptor {
	return c.inters.CTLog
}

func (c *CTLogClient) mutate(ctx context.Context, m *CTLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CTLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CTLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CTLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CTLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CTLog mutation op: %q", m.Op())
	}
}

// SubscriptionClient is a client for the Subscription schema.
type SubscriptionClient struct {
	config
}

// NewSubscriptionClient returns a client for the Subscription from the given config.
func NewSubscriptionClient(c config) *SubscriptionClient {
	return &SubscriptionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `subscription.Hooks(f(g(h())))`.
func (c *SubscriptionClient) Use(hooks ...Hook) {
	c.hooks.Subscription = append(c.hooks.Subscription, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `subscription.Intercept(f(g(h())))`.
func (c *SubscriptionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Subscription = append(c.inters.Subscription, interceptors...)
}

// Create returns a builder for creating a Subscription entity.
func (c *SubscriptionClient) Create() *SubscriptionCreate {
	mutation := newSubscriptionMutation(c.config, OpCreate)
	return &SubscriptionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Subscription entities.
func (c *SubscriptionClient) CreateBulk(builders ...*SubscriptionCreate) *SubscriptionCreateBulk {
	return &SubscriptionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SubscriptionClient) MapCreateBulk(slice any, setFunc func(*SubscriptionCreate, int)) *SubscriptionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SubscriptionCreateBulk{err: fmt.Errorf("calling to SubscriptionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SubscriptionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SubscriptionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Subscription.
func (c *SubscriptionClient) Update() *SubscriptionUpdate {
	mutation := newSubscriptionMutation(c.config, OpUpdate)
	return &SubscriptionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SubscriptionClient) UpdateOne(s *Subscription) *SubscriptionUpdateOne {
	mutation := newSubscriptionMutation(c.config, OpUpdateOne, withSubscription(s))
	return &SubscriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SubscriptionClient) UpdateOneID(id int) *SubscriptionUpdateOne {
	mutation := newSubscriptionMutation(c.config, OpUpdateOne, withSubscriptionID(id))
	return &SubscriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Subscription.
func (c *SubscriptionClient) Delete() *SubscriptionDelete {
	mutation := newSubscriptionMutation(c.config, OpDelete)
	return &SubscriptionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SubscriptionClient) DeleteOne(s *Subscription) *SubscriptionDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SubscriptionClient) DeleteOneID(id int) *SubscriptionDeleteOne {
	builder := c.Delete().Where(subscription.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SubscriptionDeleteOne{builder}
}

// Query returns a query builder for Subscription.
func (c *SubscriptionClient) Query() *SubscriptionQuery {
	return &SubscriptionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSubscription},
		inters: c.Interceptors(),
	}
}

// Get returns a Subscription entity by its id.
func (c *SubscriptionClient) Get(ctx context.Context, id int) (*Subscription, error) {
	return c.Query().Where(subscription.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SubscriptionClient) GetX(ctx context.Context, id int) *Subscription {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SubscriptionClient) Hooks() []Hook {
	return c.hooks.Subscription
}

// Interceptors returns the client interceptors.
func (c *SubscriptionClient) Interceptors() []Interceptor {
	return c.inters.Subscription
}

func (c *SubscriptionClient) mutate(ctx context.Context, m *SubscriptionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SubscriptionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SubscriptionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SubscriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SubscriptionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Subscription mutation op: %q", m.Op())
	}
}

// TAClient is a client for the TA schema.
type TAClient struct {
	config
}

// NewTAClient returns a client for the TA from the given config.
func NewTAClient(c config) *TAClient {
	return &TAClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ta.Hooks(f(g(h())))`.
func (c *TAClient) Use(hooks ...Hook) {
	c.hooks.TA = append(c.hooks.TA, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ta.Intercept(f(g(h())))`.
func (c *TAClient) Intercept(interceptors ...Interceptor) {
	c.inters.TA = append(c.inters.TA, interceptors...)
}

// Create returns a builder for creating a TA entity.
func (c *TAClient) Create() *TACreate {
	mutation := newTAMutation(c.config, OpCreate)
	return &TACreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TA entities.
func (c *TAClient) CreateBulk(builders ...*TACreate) *TACreateBulk {
	return &TACreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TAClient) MapCreateBulk(slice any, setFunc func(*TACreate, int)) *TACreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TACreateBulk{err: fmt.Errorf("calling to TAClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TACreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TACreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TA.
func (c *TAClient) Update() *TAUpdate {
	mutation := newTAMutation(c.config, OpUpdate)
	return &TAUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TAClient) UpdateOne(t *TA) *TAUpdateOne {
	mutation := newTAMutation(c.config, OpUpdateOne, withTA(t))
	return &TAUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TAClient) UpdateOneID(id int) *TAUpdateOne {
	mutation := newTAMutation(c.config, OpUpdateOne, withTAID(id))
	return &TAUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TA.
func (c *TAClient) Delete() *TADelete {
	mutation := newTAMutation(c.config, OpDelete)
	return &TADelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TAClient) DeleteOne(t *TA) *TADeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TAClient) DeleteOneID(id int) *TADeleteOne {
	builder := c.Delete().Where(ta.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TADeleteOne{builder}
}

// Query returns a query builder for TA.
func (c *TAClient) Query() *TAQuery {
	return &TAQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTA},
		inters: c.Interceptors(),
	}
}

// Get returns a TA entity by its id.
func (c *TAClient) Get(ctx context.Context, id int) (*TA, error) {
	return c.Query().Where(ta.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TAClient) GetX(ctx context.Context, id int) *TA {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryViolation queries the violation edge of a TA.
func (c *TAClient) QueryViolation(t *TA) *ViolationQuery {
	query := (&ViolationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ta.Table, ta.FieldID, id),
			sqlgraph.To(violation.Table, violation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ta.ViolationTable, ta.ViolationColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCtLog queries the ct_log edge of a TA.
func (c *TAClient) QueryCtLog(t *TA) *CTLogQuery {
	query := (&CTLogClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ta.Table, ta.FieldID, id),
			sqlgraph.To(ctlog.Table, ctlog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ta.CtLogTable, ta.CtLogColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAtLog queries the at_log edge of a TA.
func (c *TAClient) QueryAtLog(t *TA) *ATLogQuery {
	query := (&ATLogClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ta.Table, ta.FieldID, id),
			sqlgraph.To(atlog.Table, atlog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ta.AtLogTable, ta.AtLogColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TAClient) Hooks() []Hook {
	return c.hooks.TA
}

// Interceptors returns the client interceptors.
func (c *TAClient) Interceptors() []Interceptor {
	return c.inters.TA
}

func (c *TAClient) mutate(ctx context.Context, m *TAMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TACreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TAUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TAUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TADelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TA mutation op: %q", m.Op())
	}
}

// ViolationClient is a client for the Violation schema.
type ViolationClient struct {
	config
}

// NewViolationClient returns a client for the Violation from the given config.
func NewViolationClient(c config) *ViolationClient {
	return &ViolationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `violation.Hooks(f(g(h())))`.
func (c *ViolationClient) Use(hooks ...Hook) {
	c.hooks.Violation = append(c.hooks.Violation, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `violation.Intercept(f(g(h())))`.
func (c *ViolationClient) Intercept(interceptors ...Interceptor) {
	c.inters.Violation = append(c.inters.Violation, interceptors...)
}

// Create returns a builder for creating a Violation entity.
func (c *ViolationClient) Create() *ViolationCreate {
	mutation := newViolationMutation(c.config, OpCreate)
	return &ViolationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Violation entities.
func (c *ViolationClient) CreateBulk(builders ...*ViolationCreate) *ViolationCreateBulk {
	return &ViolationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ViolationClient) MapCreateBulk(slice any, setFunc func(*ViolationCreate, int)) *ViolationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ViolationCreateBulk{err: fmt.Errorf("calling to ViolationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ViolationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ViolationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Violation.
func (c *ViolationClient) Update() *ViolationUpdate {
	mutation := newViolationMutation(c.config, OpUpdate)
	return &ViolationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ViolationClient) UpdateOne(v *Violation) *ViolationUpdateOne {
	mutation := newViolationMutation(c.config, OpUpdateOne, withViolation(v))
	return &ViolationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ViolationClient) UpdateOneID(id int) *ViolationUpdateOne {
	mutation := newViolationMutation(c.config, OpUpdateOne, withViolationID(id))
	return &ViolationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Violation.
func (c *ViolationClient) Delete() *ViolationDelete {
	mutation := newViolationMutation(c.config, OpDelete)
	return &ViolationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ViolationClient) DeleteOne(v *Violation) *ViolationDeleteOne {
	return c.DeleteOneID(v.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ViolationClient) DeleteOneID(id int) *ViolationDeleteOne {
	builder := c.Delete().Where(violation.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ViolationDeleteOne{builder}
}

// Query returns a query builder for Violation.
func (c *ViolationClient) Query() *ViolationQuery {
	return &ViolationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeViolation},
		inters: c.Interceptors(),
	}
}

// Get returns a Violation entity by its id.
func (c *ViolationClient) Get(ctx context.Context, id int) (*Violation, error) {
	return c.Query().Where(violation.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ViolationClient) GetX(ctx context.Context, id int) *Violation {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTa queries the ta edge of a Violation.
func (c *ViolationClient) QueryTa(v *Violation) *TAQuery {
	query := (&TAClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := v.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(violation.Table, violation.FieldID, id),
			sqlgraph.To(ta.Table, ta.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, violation.TaTable, violation.TaColumn),
		)
		fromV = sqlgraph.Neighbors(v.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ViolationClient) Hooks() []Hook {
	return c.hooks.Violation
}

// Interceptors returns the client interceptors.
func (c *ViolationClient) Interceptors() []Interceptor {
	return c.inters.Violation
}

func (c *ViolationClient) mutate(ctx context.Context, m *ViolationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ViolationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ViolationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ViolationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ViolationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Violation mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ATLog, CTLog, Subscription, TA, Violation []ent.Hook
	}
	inters struct {
		ATLog, CTLog, Subscription, TA, Violation []ent.Interceptor
	}
)
