// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/ra-webs/monitor/ent/predicate"
	"github.com/akakou/ra-webs/monitor/ent/taviolation"
)

// TAViolationDelete is the builder for deleting a TAViolation entity.
type TAViolationDelete struct {
	config
	hooks    []Hook
	mutation *TAViolationMutation
}

// Where appends a list predicates to the TAViolationDelete builder.
func (tvd *TAViolationDelete) Where(ps ...predicate.TAViolation) *TAViolationDelete {
	tvd.mutation.Where(ps...)
	return tvd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tvd *TAViolationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tvd.sqlExec, tvd.mutation, tvd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tvd *TAViolationDelete) ExecX(ctx context.Context) int {
	n, err := tvd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tvd *TAViolationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(taviolation.Table, sqlgraph.NewFieldSpec(taviolation.FieldID, field.TypeInt))
	if ps := tvd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tvd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tvd.mutation.done = true
	return affected, err
}

// TAViolationDeleteOne is the builder for deleting a single TAViolation entity.
type TAViolationDeleteOne struct {
	tvd *TAViolationDelete
}

// Where appends a list predicates to the TAViolationDelete builder.
func (tvdo *TAViolationDeleteOne) Where(ps ...predicate.TAViolation) *TAViolationDeleteOne {
	tvdo.tvd.mutation.Where(ps...)
	return tvdo
}

// Exec executes the deletion query.
func (tvdo *TAViolationDeleteOne) Exec(ctx context.Context) error {
	n, err := tvdo.tvd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{taviolation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tvdo *TAViolationDeleteOne) ExecX(ctx context.Context) {
	if err := tvdo.Exec(ctx); err != nil {
		panic(err)
	}
}
