// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/ra-webs/monitor/ent/predicate"
	"github.com/akakou/ra-webs/monitor/ent/ta"
	"github.com/akakou/ra-webs/monitor/ent/violation"
)

// ViolationUpdate is the builder for updating Violation entities.
type ViolationUpdate struct {
	config
	hooks    []Hook
	mutation *ViolationMutation
}

// Where appends a list predicates to the ViolationUpdate builder.
func (vu *ViolationUpdate) Where(ps ...predicate.Violation) *ViolationUpdate {
	vu.mutation.Where(ps...)
	return vu
}

// SetTaID sets the "ta" edge to the TA entity by ID.
func (vu *ViolationUpdate) SetTaID(id int) *ViolationUpdate {
	vu.mutation.SetTaID(id)
	return vu
}

// SetNillableTaID sets the "ta" edge to the TA entity by ID if the given value is not nil.
func (vu *ViolationUpdate) SetNillableTaID(id *int) *ViolationUpdate {
	if id != nil {
		vu = vu.SetTaID(*id)
	}
	return vu
}

// SetTa sets the "ta" edge to the TA entity.
func (vu *ViolationUpdate) SetTa(t *TA) *ViolationUpdate {
	return vu.SetTaID(t.ID)
}

// Mutation returns the ViolationMutation object of the builder.
func (vu *ViolationUpdate) Mutation() *ViolationMutation {
	return vu.mutation
}

// ClearTa clears the "ta" edge to the TA entity.
func (vu *ViolationUpdate) ClearTa() *ViolationUpdate {
	vu.mutation.ClearTa()
	return vu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (vu *ViolationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, vu.sqlSave, vu.mutation, vu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vu *ViolationUpdate) SaveX(ctx context.Context) int {
	affected, err := vu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (vu *ViolationUpdate) Exec(ctx context.Context) error {
	_, err := vu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vu *ViolationUpdate) ExecX(ctx context.Context) {
	if err := vu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (vu *ViolationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(violation.Table, violation.Columns, sqlgraph.NewFieldSpec(violation.FieldID, field.TypeInt))
	if ps := vu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if vu.mutation.TaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   violation.TaTable,
			Columns: []string{violation.TaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ta.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.TaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   violation.TaTable,
			Columns: []string{violation.TaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, vu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{violation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	vu.mutation.done = true
	return n, nil
}

// ViolationUpdateOne is the builder for updating a single Violation entity.
type ViolationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ViolationMutation
}

// SetTaID sets the "ta" edge to the TA entity by ID.
func (vuo *ViolationUpdateOne) SetTaID(id int) *ViolationUpdateOne {
	vuo.mutation.SetTaID(id)
	return vuo
}

// SetNillableTaID sets the "ta" edge to the TA entity by ID if the given value is not nil.
func (vuo *ViolationUpdateOne) SetNillableTaID(id *int) *ViolationUpdateOne {
	if id != nil {
		vuo = vuo.SetTaID(*id)
	}
	return vuo
}

// SetTa sets the "ta" edge to the TA entity.
func (vuo *ViolationUpdateOne) SetTa(t *TA) *ViolationUpdateOne {
	return vuo.SetTaID(t.ID)
}

// Mutation returns the ViolationMutation object of the builder.
func (vuo *ViolationUpdateOne) Mutation() *ViolationMutation {
	return vuo.mutation
}

// ClearTa clears the "ta" edge to the TA entity.
func (vuo *ViolationUpdateOne) ClearTa() *ViolationUpdateOne {
	vuo.mutation.ClearTa()
	return vuo
}

// Where appends a list predicates to the ViolationUpdate builder.
func (vuo *ViolationUpdateOne) Where(ps ...predicate.Violation) *ViolationUpdateOne {
	vuo.mutation.Where(ps...)
	return vuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (vuo *ViolationUpdateOne) Select(field string, fields ...string) *ViolationUpdateOne {
	vuo.fields = append([]string{field}, fields...)
	return vuo
}

// Save executes the query and returns the updated Violation entity.
func (vuo *ViolationUpdateOne) Save(ctx context.Context) (*Violation, error) {
	return withHooks(ctx, vuo.sqlSave, vuo.mutation, vuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vuo *ViolationUpdateOne) SaveX(ctx context.Context) *Violation {
	node, err := vuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (vuo *ViolationUpdateOne) Exec(ctx context.Context) error {
	_, err := vuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vuo *ViolationUpdateOne) ExecX(ctx context.Context) {
	if err := vuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (vuo *ViolationUpdateOne) sqlSave(ctx context.Context) (_node *Violation, err error) {
	_spec := sqlgraph.NewUpdateSpec(violation.Table, violation.Columns, sqlgraph.NewFieldSpec(violation.FieldID, field.TypeInt))
	id, ok := vuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Violation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := vuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, violation.FieldID)
		for _, f := range fields {
			if !violation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != violation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := vuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if vuo.mutation.TaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   violation.TaTable,
			Columns: []string{violation.TaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ta.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.TaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   violation.TaTable,
			Columns: []string{violation.TaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Violation{config: vuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, vuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{violation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	vuo.mutation.done = true
	return _node, nil
}
