// Code generated by ent, DO NOT EDIT.

package ctaudit

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/akakou/ra_webs/ttp/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldLTE(FieldID, id))
}

// CtValid applies equality check predicate on the "ct_valid" field. It's identical to CtValidEQ.
func CtValid(v bool) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldEQ(FieldCtValid, v))
}

// LastCt applies equality check predicate on the "last_ct" field. It's identical to LastCtEQ.
func LastCt(v string) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldEQ(FieldLastCt, v))
}

// CtValidEQ applies the EQ predicate on the "ct_valid" field.
func CtValidEQ(v bool) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldEQ(FieldCtValid, v))
}

// CtValidNEQ applies the NEQ predicate on the "ct_valid" field.
func CtValidNEQ(v bool) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldNEQ(FieldCtValid, v))
}

// LastCtEQ applies the EQ predicate on the "last_ct" field.
func LastCtEQ(v string) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldEQ(FieldLastCt, v))
}

// LastCtNEQ applies the NEQ predicate on the "last_ct" field.
func LastCtNEQ(v string) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldNEQ(FieldLastCt, v))
}

// LastCtIn applies the In predicate on the "last_ct" field.
func LastCtIn(vs ...string) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldIn(FieldLastCt, vs...))
}

// LastCtNotIn applies the NotIn predicate on the "last_ct" field.
func LastCtNotIn(vs ...string) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldNotIn(FieldLastCt, vs...))
}

// LastCtGT applies the GT predicate on the "last_ct" field.
func LastCtGT(v string) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldGT(FieldLastCt, v))
}

// LastCtGTE applies the GTE predicate on the "last_ct" field.
func LastCtGTE(v string) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldGTE(FieldLastCt, v))
}

// LastCtLT applies the LT predicate on the "last_ct" field.
func LastCtLT(v string) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldLT(FieldLastCt, v))
}

// LastCtLTE applies the LTE predicate on the "last_ct" field.
func LastCtLTE(v string) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldLTE(FieldLastCt, v))
}

// LastCtContains applies the Contains predicate on the "last_ct" field.
func LastCtContains(v string) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldContains(FieldLastCt, v))
}

// LastCtHasPrefix applies the HasPrefix predicate on the "last_ct" field.
func LastCtHasPrefix(v string) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldHasPrefix(FieldLastCt, v))
}

// LastCtHasSuffix applies the HasSuffix predicate on the "last_ct" field.
func LastCtHasSuffix(v string) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldHasSuffix(FieldLastCt, v))
}

// LastCtEqualFold applies the EqualFold predicate on the "last_ct" field.
func LastCtEqualFold(v string) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldEqualFold(FieldLastCt, v))
}

// LastCtContainsFold applies the ContainsFold predicate on the "last_ct" field.
func LastCtContainsFold(v string) predicate.CTAudit {
	return predicate.CTAudit(sql.FieldContainsFold(FieldLastCt, v))
}

// HasTa applies the HasEdge predicate on the "ta" edge.
func HasTa() predicate.CTAudit {
	return predicate.CTAudit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, TaTable, TaColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaWith applies the HasEdge predicate on the "ta" edge with a given conditions (other predicates).
func HasTaWith(preds ...predicate.TA) predicate.CTAudit {
	return predicate.CTAudit(func(s *sql.Selector) {
		step := newTaStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CTAudit) predicate.CTAudit {
	return predicate.CTAudit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CTAudit) predicate.CTAudit {
	return predicate.CTAudit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CTAudit) predicate.CTAudit {
	return predicate.CTAudit(sql.NotPredicates(p))
}
