// Code generated by ent, DO NOT EDIT.

package tacode

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tacode type in the database.
	Label = "ta_code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRepository holds the string denoting the repository field in the database.
	FieldRepository = "repository"
	// FieldCommitID holds the string denoting the commit_id field in the database.
	FieldCommitID = "commit_id"
	// FieldUniqueID holds the string denoting the unique_id field in the database.
	FieldUniqueID = "unique_id"
	// FieldActivate holds the string denoting the activate field in the database.
	FieldActivate = "activate"
	// EdgeTa holds the string denoting the ta edge name in mutations.
	EdgeTa = "ta"
	// Table holds the table name of the tacode in the database.
	Table = "ta_codes"
	// TaTable is the table that holds the ta relation/edge.
	TaTable = "tas"
	// TaInverseTable is the table name for the TA entity.
	// It exists in this package in order to avoid circular dependency with the "ta" package.
	TaInverseTable = "tas"
	// TaColumn is the table column denoting the ta relation/edge.
	TaColumn = "ta_code"
)

// Columns holds all SQL columns for tacode fields.
var Columns = []string{
	FieldID,
	FieldRepository,
	FieldCommitID,
	FieldUniqueID,
	FieldActivate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultActivate holds the default value on creation for the "activate" field.
	DefaultActivate bool
)

// OrderOption defines the ordering options for the TACode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepository orders the results by the repository field.
func ByRepository(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepository, opts...).ToFunc()
}

// ByCommitID orders the results by the commit_id field.
func ByCommitID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommitID, opts...).ToFunc()
}

// ByActivate orders the results by the activate field.
func ByActivate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivate, opts...).ToFunc()
}

// ByTaCount orders the results by ta count.
func ByTaCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTaStep(), opts...)
	}
}

// ByTa orders the results by ta terms.
func ByTa(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TaTable, TaColumn),
	)
}
