// Code generated by ent, DO NOT EDIT.

package tacode

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tacode type in the database.
	Label = "ta_code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUniqueID holds the string denoting the unique_id field in the database.
	FieldUniqueID = "unique_id"
	// FieldCommitID holds the string denoting the commit_id field in the database.
	FieldCommitID = "commit_id"
	// EdgeTaInfo holds the string denoting the ta_info edge name in mutations.
	EdgeTaInfo = "ta_info"
	// Table holds the table name of the tacode in the database.
	Table = "ta_codes"
	// TaInfoTable is the table that holds the ta_info relation/edge. The primary key declared below.
	TaInfoTable = "ta_code_ta_info"
	// TaInfoInverseTable is the table name for the TAInfo entity.
	// It exists in this package in order to avoid circular dependency with the "tainfo" package.
	TaInfoInverseTable = "ta_infos"
)

// Columns holds all SQL columns for tacode fields.
var Columns = []string{
	FieldID,
	FieldUniqueID,
	FieldCommitID,
}

var (
	// TaInfoPrimaryKey and TaInfoColumn2 are the table columns denoting the
	// primary key for the ta_info relation (M2M).
	TaInfoPrimaryKey = []string{"ta_code_id", "ta_info_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the TACode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUniqueID orders the results by the unique_id field.
func ByUniqueID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUniqueID, opts...).ToFunc()
}

// ByCommitID orders the results by the commit_id field.
func ByCommitID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommitID, opts...).ToFunc()
}

// ByTaInfoCount orders the results by ta_info count.
func ByTaInfoCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTaInfoStep(), opts...)
	}
}

// ByTaInfo orders the results by ta_info terms.
func ByTaInfo(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaInfoStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTaInfoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaInfoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, TaInfoTable, TaInfoPrimaryKey...),
	)
}
