// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AtLogsColumns holds the columns for the "at_logs" table.
	AtLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "evidence", Type: field.TypeString},
		{Name: "repository", Type: field.TypeString},
		{Name: "commit_id", Type: field.TypeString},
		{Name: "unique_id", Type: field.TypeBytes},
		{Name: "is_active", Type: field.TypeBool, Default: false},
		{Name: "at_log_ta", Type: field.TypeInt, Nullable: true},
	}
	// AtLogsTable holds the schema information for the "at_logs" table.
	AtLogsTable = &schema.Table{
		Name:       "at_logs",
		Columns:    AtLogsColumns,
		PrimaryKey: []*schema.Column{AtLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "at_logs_tas_ta",
				Columns:    []*schema.Column{AtLogsColumns[6]},
				RefColumns: []*schema.Column{TasColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CtLogsColumns holds the columns for the "ct_logs" table.
	CtLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "public_key", Type: field.TypeBytes},
		{Name: "monitor_log_id", Type: field.TypeInt},
		{Name: "is_active", Type: field.TypeBool, Default: false},
		{Name: "ct_log_ta", Type: field.TypeInt, Nullable: true},
	}
	// CtLogsTable holds the schema information for the "ct_logs" table.
	CtLogsTable = &schema.Table{
		Name:       "ct_logs",
		Columns:    CtLogsColumns,
		PrimaryKey: []*schema.Column{CtLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ct_logs_tas_ta",
				Columns:    []*schema.Column{CtLogsColumns[4]},
				RefColumns: []*schema.Column{TasColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SubscriptionsColumns holds the columns for the "subscriptions" table.
	SubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "endpoint", Type: field.TypeString},
		{Name: "p256dh", Type: field.TypeString},
		{Name: "auth", Type: field.TypeString},
	}
	// SubscriptionsTable holds the schema information for the "subscriptions" table.
	SubscriptionsTable = &schema.Table{
		Name:       "subscriptions",
		Columns:    SubscriptionsColumns,
		PrimaryKey: []*schema.Column{SubscriptionsColumns[0]},
	}
	// TasColumns holds the columns for the "tas" table.
	TasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "public_key", Type: field.TypeBytes},
	}
	// TasTable holds the schema information for the "tas" table.
	TasTable = &schema.Table{
		Name:       "tas",
		Columns:    TasColumns,
		PrimaryKey: []*schema.Column{TasColumns[0]},
	}
	// ViolationsColumns holds the columns for the "violations" table.
	ViolationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "violation_ta", Type: field.TypeInt, Nullable: true},
	}
	// ViolationsTable holds the schema information for the "violations" table.
	ViolationsTable = &schema.Table{
		Name:       "violations",
		Columns:    ViolationsColumns,
		PrimaryKey: []*schema.Column{ViolationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "violations_tas_ta",
				Columns:    []*schema.Column{ViolationsColumns[2]},
				RefColumns: []*schema.Column{TasColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AtLogsTable,
		CtLogsTable,
		SubscriptionsTable,
		TasTable,
		ViolationsTable,
	}
)

func init() {
	AtLogsTable.ForeignKeys[0].RefTable = TasTable
	CtLogsTable.ForeignKeys[0].RefTable = TasTable
	ViolationsTable.ForeignKeys[0].RefTable = TasTable
}
