// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AtLogsColumns holds the columns for the "at_logs" table.
	AtLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "evidence", Type: field.TypeString},
		{Name: "repository", Type: field.TypeString},
		{Name: "commit_id", Type: field.TypeString},
		{Name: "unique_id", Type: field.TypeBytes},
		{Name: "is_active", Type: field.TypeBool, Default: false},
		{Name: "ct_log_at_log", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// AtLogsTable holds the schema information for the "at_logs" table.
	AtLogsTable = &schema.Table{
		Name:       "at_logs",
		Columns:    AtLogsColumns,
		PrimaryKey: []*schema.Column{AtLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "at_logs_ct_logs_at_log",
				Columns:    []*schema.Column{AtLogsColumns[6]},
				RefColumns: []*schema.Column{CtLogsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CtLogsColumns holds the columns for the "ct_logs" table.
	CtLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "public_key", Type: field.TypeBytes},
		{Name: "monitor_log_id", Type: field.TypeInt},
		{Name: "is_active", Type: field.TypeBool, Default: false},
	}
	// CtLogsTable holds the schema information for the "ct_logs" table.
	CtLogsTable = &schema.Table{
		Name:       "ct_logs",
		Columns:    CtLogsColumns,
		PrimaryKey: []*schema.Column{CtLogsColumns[0]},
	}
	// SubscriptionsColumns holds the columns for the "subscriptions" table.
	SubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "endpoint", Type: field.TypeString},
		{Name: "p256dh", Type: field.TypeString},
		{Name: "auth", Type: field.TypeString},
		{Name: "subscription_ct_log", Type: field.TypeInt, Nullable: true},
	}
	// SubscriptionsTable holds the schema information for the "subscriptions" table.
	SubscriptionsTable = &schema.Table{
		Name:       "subscriptions",
		Columns:    SubscriptionsColumns,
		PrimaryKey: []*schema.Column{SubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "subscriptions_ct_logs_ct_log",
				Columns:    []*schema.Column{SubscriptionsColumns[4]},
				RefColumns: []*schema.Column{CtLogsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TaViolationsColumns holds the columns for the "ta_violations" table.
	TaViolationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "ta_violation_ct_log", Type: field.TypeInt, Nullable: true},
	}
	// TaViolationsTable holds the schema information for the "ta_violations" table.
	TaViolationsTable = &schema.Table{
		Name:       "ta_violations",
		Columns:    TaViolationsColumns,
		PrimaryKey: []*schema.Column{TaViolationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ta_violations_ct_logs_ct_log",
				Columns:    []*schema.Column{TaViolationsColumns[2]},
				RefColumns: []*schema.Column{CtLogsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AtLogsTable,
		CtLogsTable,
		SubscriptionsTable,
		TaViolationsTable,
	}
)

func init() {
	AtLogsTable.ForeignKeys[0].RefTable = CtLogsTable
	SubscriptionsTable.ForeignKeys[0].RefTable = CtLogsTable
	TaViolationsTable.ForeignKeys[0].RefTable = CtLogsTable
}
