// Code generated by ent, DO NOT EDIT.

package service

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the service type in the database.
	Label = "service"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// EdgeTaserver holds the string denoting the taserver edge name in mutations.
	EdgeTaserver = "taserver"
	// EdgeTacode holds the string denoting the tacode edge name in mutations.
	EdgeTacode = "tacode"
	// Table holds the table name of the service in the database.
	Table = "services"
	// TaserverTable is the table that holds the taserver relation/edge.
	TaserverTable = "ta_servers"
	// TaserverInverseTable is the table name for the TAServer entity.
	// It exists in this package in order to avoid circular dependency with the "taserver" package.
	TaserverInverseTable = "ta_servers"
	// TaserverColumn is the table column denoting the taserver relation/edge.
	TaserverColumn = "ta_server_service"
	// TacodeTable is the table that holds the tacode relation/edge.
	TacodeTable = "ta_codes"
	// TacodeInverseTable is the table name for the TACode entity.
	// It exists in this package in order to avoid circular dependency with the "tacode" package.
	TacodeInverseTable = "ta_codes"
	// TacodeColumn is the table column denoting the tacode relation/edge.
	TacodeColumn = "ta_code_service"
)

// Columns holds all SQL columns for service fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldToken,
	FieldIsActive,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
)

// OrderOption defines the ordering options for the Service queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByTaserverCount orders the results by taserver count.
func ByTaserverCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTaserverStep(), opts...)
	}
}

// ByTaserver orders the results by taserver terms.
func ByTaserver(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaserverStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTacodeCount orders the results by tacode count.
func ByTacodeCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTacodeStep(), opts...)
	}
}

// ByTacode orders the results by tacode terms.
func ByTacode(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTacodeStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTaserverStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaserverInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TaserverTable, TaserverColumn),
	)
}
func newTacodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TacodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TacodeTable, TacodeColumn),
	)
}
