// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CTLogAudit is the predicate function for ctlogaudit builders.
type CTLogAudit func(*sql.Selector)

// TACode is the predicate function for tacode builders.
type TACode func(*sql.Selector)

// TAInfo is the predicate function for tainfo builders.
type TAInfo func(*sql.Selector)
