// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TA is the predicate function for ta builders.
type TA func(*sql.Selector)

// TAAuditLog is the predicate function for taauditlog builders.
type TAAuditLog func(*sql.Selector)

// TACode is the predicate function for tacode builders.
type TACode func(*sql.Selector)
