// Code generated by ent, DO NOT EDIT.

package ctlogaudit

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/akakou/ra_webs/ttp/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldLTE(FieldID, id))
}

// IsValid applies equality check predicate on the "is_valid" field. It's identical to IsValidEQ.
func IsValid(v bool) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldEQ(FieldIsValid, v))
}

// LatestCtID applies equality check predicate on the "latest_ct_id" field. It's identical to LatestCtIDEQ.
func LatestCtID(v string) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldEQ(FieldLatestCtID, v))
}

// IsValidEQ applies the EQ predicate on the "is_valid" field.
func IsValidEQ(v bool) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldEQ(FieldIsValid, v))
}

// IsValidNEQ applies the NEQ predicate on the "is_valid" field.
func IsValidNEQ(v bool) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldNEQ(FieldIsValid, v))
}

// LatestCtIDEQ applies the EQ predicate on the "latest_ct_id" field.
func LatestCtIDEQ(v string) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldEQ(FieldLatestCtID, v))
}

// LatestCtIDNEQ applies the NEQ predicate on the "latest_ct_id" field.
func LatestCtIDNEQ(v string) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldNEQ(FieldLatestCtID, v))
}

// LatestCtIDIn applies the In predicate on the "latest_ct_id" field.
func LatestCtIDIn(vs ...string) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldIn(FieldLatestCtID, vs...))
}

// LatestCtIDNotIn applies the NotIn predicate on the "latest_ct_id" field.
func LatestCtIDNotIn(vs ...string) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldNotIn(FieldLatestCtID, vs...))
}

// LatestCtIDGT applies the GT predicate on the "latest_ct_id" field.
func LatestCtIDGT(v string) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldGT(FieldLatestCtID, v))
}

// LatestCtIDGTE applies the GTE predicate on the "latest_ct_id" field.
func LatestCtIDGTE(v string) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldGTE(FieldLatestCtID, v))
}

// LatestCtIDLT applies the LT predicate on the "latest_ct_id" field.
func LatestCtIDLT(v string) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldLT(FieldLatestCtID, v))
}

// LatestCtIDLTE applies the LTE predicate on the "latest_ct_id" field.
func LatestCtIDLTE(v string) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldLTE(FieldLatestCtID, v))
}

// LatestCtIDContains applies the Contains predicate on the "latest_ct_id" field.
func LatestCtIDContains(v string) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldContains(FieldLatestCtID, v))
}

// LatestCtIDHasPrefix applies the HasPrefix predicate on the "latest_ct_id" field.
func LatestCtIDHasPrefix(v string) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldHasPrefix(FieldLatestCtID, v))
}

// LatestCtIDHasSuffix applies the HasSuffix predicate on the "latest_ct_id" field.
func LatestCtIDHasSuffix(v string) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldHasSuffix(FieldLatestCtID, v))
}

// LatestCtIDEqualFold applies the EqualFold predicate on the "latest_ct_id" field.
func LatestCtIDEqualFold(v string) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldEqualFold(FieldLatestCtID, v))
}

// LatestCtIDContainsFold applies the ContainsFold predicate on the "latest_ct_id" field.
func LatestCtIDContainsFold(v string) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.FieldContainsFold(FieldLatestCtID, v))
}

// HasTaInfo applies the HasEdge predicate on the "ta_info" edge.
func HasTaInfo() predicate.CTLogAudit {
	return predicate.CTLogAudit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, TaInfoTable, TaInfoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaInfoWith applies the HasEdge predicate on the "ta_info" edge with a given conditions (other predicates).
func HasTaInfoWith(preds ...predicate.TAInfo) predicate.CTLogAudit {
	return predicate.CTLogAudit(func(s *sql.Selector) {
		step := newTaInfoStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CTLogAudit) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CTLogAudit) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CTLogAudit) predicate.CTLogAudit {
	return predicate.CTLogAudit(sql.NotPredicates(p))
}
